"""
ربات نرخ لحظه‌ای دلار
- /start در پیوی: انتخاب مقصد (خودم / گروه / کانال) و تنظیم بازه‌ی زمانی و فاصله‌ی ارسال
- استیکر شیشه‌ای کم‌رنگ: سفید = ثابت ، سبز = بالا ، قرمز = پایین (با قیمت دقیق و مقدار تغییر)
"""
import base64
import io
import json
import os
import re
import time
import traceback
from datetime import datetime, timedelta, timezone
from html import unescape
from html.parser import HTMLParser

import requests
from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont, ImageOps

# ====== تنظیمات ======
BOT_TOKEN = os.environ.get("BOT_TOKEN", "").strip()  # فقط از متغیر محیطی
if not BOT_TOKEN:
    raise SystemExit("BOT_TOKEN تنظیم نشده — در Railway Variables بگذار")
WATERMARK = "@Arka_money_bot"          # لینکی که زیر استیکر نوشته میشه
ADMIN_ID = int(os.environ.get("ADMIN_ID", "8602292046"))  # ادمین پنل مدیریت
PROXY = os.environ.get("PROXY", "")  # فقط برای اتصال شبکه در صورت نیاز
# ======================

BASE = os.path.dirname(os.path.abspath(__file__))
STATE_FILE = os.environ.get("STATE_FILE", os.path.join(BASE, "state.json"))
PROXIES = {"http": PROXY, "https": PROXY} if PROXY else None
API = f"https://api.telegram.org/bot{BOT_TOKEN}/"
BOT_ID = 0
BOT_NAME = ""
_PC = {"ts": 0, "price": None}  # کش قیمت — نباید حذف شود
_SRC = {"last_post": 0, "last_price": None, "last_check": 0}

FONT_B64 = (
    "AAEAAAARAQAABAAQR0RFRgDfAUEAAFTgAAAAIkdQT1NEdkx1AABVBAAAACBHU1VCJ6Q/wwAAVSQAAACWT1MvMmss8GAAAAGYAAAA"
    "VmNtYXDzwvuYAAAD7AAAAKxjdnQgPrkxCAAADOwAAAJUZnBnbVsCa/AAAASYAAAArGdhc3AABwAHAABU1AAAAAxnbHlm9wwNcgAA"
    "EEAAAEJyaGVhZChqTDwAAAEcAAAANmhoZWEOrwfwAAABVAAAACRobXR4cv0zOQAAAfAAAAH8bG9jYXq2i/MAAA9AAAABAG1heHAG"
    "xAYtAAABeAAAACBuYW1lLAxBcgAAUrQAAAH+cG9zdP/bAFoAAFS0AAAAIHByZXB8YaLnAAAFRAAAB6cAAQAAAAJeuMzHOMRfDzz1"
    "AB8IAAAAAADg+tE5AAAAAOD60Tn3cvyuD80JZwABAAgAAgAAAAAAAAABAAAHbf4dAAAQIfdy+TIPzQABAAAAAAAAAAAAAAAAAAAA"
    "fwABAAAAfwNOACsAeAAMAAIAEABAAAgAAAXtAiEACAAEAAEElQK8AAUAAAUzBZkAAAEeBTMFmQAAA9cAZgISAAACCwgDAwYEAgIE"
    "AAAAAYAAAAAAAAAIAAAAAFBmRWQAIAAg/u4GFP4UAZoHbQHjAAAAAQAAAAAAAATNAGYCyQAAA6YBHwQrAMMGtACLBZEAoAgEAEIG"
    "+gB7AnMAwwOoALADqACkBC8AKQa0ANkDCgBtA1IAbwMKANEC7AAABZEAYgWRAOcFkQCiBZEAiQWRAFwFkQCeBZEAfwWRAIkFkQB9"
    "BZEAagMzAOUDMwCBBrQA2Qa0ANkGtADZBKQAjQgAAIcGMQAKBhkAvAXfAGYGpAC8BXcAvAV3ALwGkQBmBrIAvAL6ALwC+v+NBjMA"
    "vAUZALwH9gC8BrIAvAbNAGYF3QC8Bs0AZgYpALwFwwCTBXUACgZ/ALwGMQAKCNMAPQYrACcFy//sBc0AXAOoALAC7AAAA6gAiwa0"
    "AM8EAAAABAAAXgVmAFgFugCsBL4AWAW6AFwFbQBYA3sAJwW6AFwFsgCsAr4ArAK+/7wFUgCsAr4ArAhWAKoFsgCsBX8AWAW6AKwF"
    "ugBcA/IArATDAGoD0wAbBbIAoAU3AB8HZABIBSkAHwU3ABkEqABcBbIBAALsAQQFsgEABrQA2QK+AKwFxACdBBsAfQSb/6sG1AB+"
    "AwH/7AMB/+wDRP/sAwH/7AK+AKwDAQCsAwH/7AMB/+wDRP/sBcQAnQQbAH0Em/+rBPr/qwSb/6sIJP/sAwH/7AT0/+wG1AB+AwH/"
    "7ATaAIUFBP+sAJYAAAGQAAABkAAAAwH/7ANE/+wAAAACAAAAAwAAABQAAwABAAAAFAAEAJgAAAAiACAABAACAH77WPv+/o7+kf6Y"
    "/qX+qf6v/rT+3/7j/uX+5/7q/u7//wAAACD7WPv+/o3+kf6X/qX+qf6t/rT+3/7j/uX+5/7q/u7////hBQ0EagHcAdoB1QHJAcYB"
    "wwG/AZUBkgGRAZABjgGLAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtwcGBQQDAgEALCAQsAIlSWSwQFFYIMhZ"
    "IS0ssAIlSWSwQFFYIMhZIS0sIBAHILAAULANeSC4//9QWAQbBVmwBRywAyUIsAQlI+EgsABQsA15ILj//1BYBBsFWbAFHLADJQjh"
    "LSxLUFgguAEoRURZIS0ssAIlRWBELSxLU1iwAiWwAiVFRFkhIS0sRUQtLLACJbACJUmwBSWwBSVJYLAgY2ggihCKIzqKEGU6LUGE"
    "AoABJgD+AAMBJQARAAMBJAEhADoABQEkAPoAAwEjABYAAwEiASEAOgAFASIA/gADASEAOgADASAA+gADAR8AuwADAR4AZAADAR0A"
    "/gADARwAGQADARsAHgADARoA/gADARkA/gADARgA/gADARcA/gADARYA/gADARUBFAAOAAUBFQD+AAMBFAAOAAMBEwD+AAMBEgD+"
    "AAMBDwEOAH0ABQEPAP4AAwEOAH0AAwENAQwAjAAFAQ0A/gADAQ0AwAAEAQwBCwBZAAUBDACMAAMBDACAAAQBCwEKACYABQELAFkA"
    "AwELAEAABAEKACYAAwEJAP4AAwEIAP4AAwEHAAwAAwEHAIAABAEGspcuBUETAQYA+gADAQUA+gADAQQA/gADAQMAGQADAQIA+gAD"
    "AQEA+gADAQBA/30D/z4D/v4D/PssBfz+A/ssA/r+A/n4RwX5fQP4RwP3+gP2/gP1/gP0/gPzuwPy/gPx/gPw/gPvHgPu/gPt7AoF"
    "7f4D7AoD7EAE6+oKBesyA+oKA+n6A+iRFgXo/gPn+gPm+gPlkRYF5f4D5P4D4/4D4v4D4f4D4P4D3/4D3voD3dwYBd1kA9wYA9ug"
    "HgXbZAPa2SUF2voD2SUD2NElBdj6A9fWFAXXFgPW1RAF1hQD1RAD1NMLBdQgA9MLA9LRJQXS+gPRkRYF0SUD0JQMBdAjA8/OFAXP"
    "JgPOzRIFzhQDzRIDzJEWBcwdA8sUA8rJuwXK/gPJyF0FybsDyYAEyED/xyUFyF0DyEAExyUDxv4DxWQDxJAQBcT+A8McA8L+A8H+"
    "A8C/OgXA+gO/rRsFvzoDvr0aBb4yA728EQW9GgO8uw8FvBEDu7oMBbsPA7oMA7mRFgW5/gO4/gO3FQO2EgO1/gO0/gOz/gOyFwOx"
    "GQOwFgOvrRsFr/oDrq0bBa76A62RFgWtGwOskRYFrH0Dq/4DqiYDqf4DqP4Dp/4Dpv4DpQoDpP4Do6IOBaP+A6IOA6JABKGgHgWh"
    "+gOgkRYFoB4Dn5EWBZ/6A56UDAWeHAOd/gOcm7sFnP4Dm5pdBZu7A5uABJqPJQWaXQOaQASZ/gOYly4FmP4Dly4DlpEWBZYeQP8D"
    "lZQMBZUgA5QMA5ORFgWTSwOSkRYFkv4DkZAQBZEWA5AQA48lA47+A43+A4z+A4v+A4r+A4n+A4iHJQWI/gOHJQOG/gOF/gOEMgOD"
    "lgOC/gOB/gOAGQN/CgN+/gN9/gN8/gN7+gN6+gN5/gN3dqYFd/4DdqYDdXQbBXX6A3QbA3P6A3J9A3H+A3BvLAVvLANu+gNt+gNs"
    "+gNr/gNq/gNp/gNoYwwFaDIDZ/4DZjIDZWQKBWX+A2QKA2RABGNiCgVjDANiCgNhYBUFYZYDYAERBWAVA18KA17+A13+A1wBEQVc"
    "/gNbWhsFW/4DWgERBVobA1n+A1j6A1f+A1YBEQVA/1b+A1X+A1QeA1MUA1JRGQVS+gNRAREFURkDUE8ZBVD6A09OEQVPGQNOEQNN"
    "HgNMSxQFTBUDS0oRBUsUA0pJDgVKEQNJDgNI+gNHRhQFRxUDRhQDRfoDREMOBUQPA0MOA0JBJQVC+gNBAREFQSUDQD8PBUD+Az8+"
    "DgU/DwM+DgM9PA0FPRYDPA0DO2QDOv4DORQDOP4DNxMDNjUaBTYlAzU0FAU1GgM1wAQ0Cg0FNBQDNIAEMzIMBTMUAzNABDIMAzEw"
    "pgUx/gMwAREFMKYDLwwDLhMDLSw6BS36AywVJQUsOgMrZAMqZAMp/gMoFQMnFxEFJx4DJiADJR4DJCMRBUArJB4DIxEDIgANBSL6"
    "AyEPAyFABCAUAx8KAx4eAx0cGQUdJQMcDxMFHBkDHLgBAECRBBsNAxoZSwUafQMZAREFGUsDGP4DFxEDFhUlBRb6AxUBEQUVJQMU"
    "ZAMTEQMS/gMRAREFEf4DEGQDDw4QBQ8TAw/ABA4QAw6ABA0BEQUN+gMMMgMLCg0FCxYDC4AECg0DCkAECf4DCP4DB/4DBgUKBQb+"
    "AwUKAwVABAT6AwNkAwIBEQUC/gMBAA0FAREDAA0DAbgBZIWNASsrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr"
    "KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr"
    "KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr"
    "KysrKysrKysrKysAKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr"
    "KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr"
    "KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr"
    "KysrKysrHQABZgEzAWYAvADpAAABPQCiAPoDHwACAAIAZgFmAAIAAgCsAVQA7AC8AGIBZgGBBIUBVAFmAW0EpAACAWYAfwTNAAAA"
    "AgEzAGIAcQAAACUEpAG8ALoA5QBmAYEBjQVIBVoBZgFtAAAAAAACAAIA9gXDAfAFOQI5AFgEbQQ9BLIEgQSyAWYBdQRmBIEAsARm"
    "BDkC0QScBHsEzwR7AFgBMwFmAUwBZgFMAAIArACaAUoBIwCaApoBRAEZAUQCzQDBAAABZgE/AZoBOwXLBcsA1QDVAVAArACsAHcC"
    "CgHHAfIBLwFYAbIBIwD2APYBHwEvATUCNQHuAecBMwCYANEDWAUKAJoAjwESAJgAvADNAOUA5QDyAHMEAAFmAI8F1QIrBdUAwwDh"
    "ANcA5QAAAGoBAgAAAB0DLQXVBdUF8ACoAGoA7ADhAQIF1QYUByEEZgL4AOwBgwKmAvgBIwECAQIBEgEfAx8AXgPNBGAExwSJAOwB"
    "vAC6AQIDMwMfA0IDMwNcARIBHwXVAZoAmgDhBmYBeQRgBGAEYAR7AAAA7ALDArgCzQC+AN0A1QAAAGoCXAJ7ApoA3QGuAboBEgAA"
    "AIUBrgRgB2IEGwCaBpoEWADuAJoCmgDRAs0BmgFQBcsFywCLAIsGMQD2BAYA8ANMAWAEqADBAAAAJQXBAQABIQdKBhIAlgFKB4MA"
    "qAAAAzcAewAUAAAAyQEABcEFwQXBBcEBAAEIBh0AlgQnA54A7AECAn0BMwCYANEDWAF5AM0COQNiAJwAnACcAJMBuACTALgAcwAA"
    "FAADJgAAACUAJQBOAHEA0wFdAdwCxgLeAwsDNgN/A6kDxwPeA/QEDAROBHsE7AVPBY8F3wY5Bm8G3Qc2B1kHhAepB8oH7QhJCPUJ"
    "kgnxCjwKgAqyCt4LOAtxC5ULzgwrDEcMzQ0kDW0Nqg4QDoUPGA9FD4EP2BCxEUoRrRH2EhgSMRJTEnUSiRLAE0kTlhPfFCwUgRTL"
    "FTEVdBWdFdkWOxZYFscXChdPF50X7BgoGNQZLRl1GfQa1BuwHGscxx0oHT4doB3iHfAeJx5LHm0enx6rHsce6x73Hv8fHB8oHzQf"
    "QB9MH1QfXB+MH5gf7SAIIE8gWyBnIKYg9iEBIRIhKSExITkAAgBm/pYEZgWkAAMABwAfvAAEASYAAAAGASa2AQgFiQIEAC/E1Owx"
    "ABDU7NTsMBMRIRElIREhZgQA/HMDG/zl/pYHDvjycgYpAAACAR8AAAKHBdUABQAJAB9ADwOMBosAjQgEAwcBAgYAChDUPOwyOTkx"
    "AC/k/OwwASERAyEDESERIQEfAWgz/v4zAWj+mAXV/cP+XgGi/cz+nAAAAgDDA6oDaAXVAAMABwAeQA8FAY4EAI0IAAQCBAQGAwgQ"
    "/Pzc7DEAEPQ87DIwAREjESMRIxEDaO3L7QXV/dUCK/3VAisAAAIAiwAABikFvgAbAB8AS0AxGQUBkhwXBxMPC5IeFQkDAI8RDR8e"
    "HRwbGhgXFhMSERAPDg0MCgkIBQQDAgEAGgYUIBDUzBc5MQAvPOQy1Dw87DIy1Dw87DIyMAEDIRMzAyEVIQMhFSEDIxMhAyMTITUh"
    "EyE1IRMBIQMhA49gAQhh3WEBFf62RQEc/rBg3WD++GDfYP7pAUhG/uUBUmABUP74RgEIBb7+fwGB/n/V/u7X/oEBf/6BAX/XARLV"
    "AYH9qv7uAAADAKD+0wUGBhQAIwAqADEAc0A/HAoGJRsYERcUJAsdKwQYBgksIwIFlgaVLBeWGJUbkxIULJMAAgsoAR0vAAUOBigk"
    "EQkDAQcrGxMDAC8GFyAyENTE/NQXPPwXPNT8xBESORESOTEAL8Ts1MT89OwQ9e4RORE5ERIXORESORESORI5OTABIwMuAScRHgEX"
    "EScuATU0Nj8BMxUeARcVLgEnERceARUUBgcDEQ4BFRQWExE+ATU0JgMbogF96m9z63kh78n14wGiZMhlZMhlIP7N9PeiR1VO8FdX"
    "UP7TAS0FLikBBjs/BAE3Biq0qbPJCefjCCIb/iovBf7hBii7t7jFDgNCAQUERTU7Q/6x/uoBQkJEQwAFAEL/4wfDBfAACwAXABsA"
    "JwAzAGNANRsLGhoZGQsYGBslAJ0MLp0imSidGgadDJkYEpgcGpw0GTErGwkDCBUJCQgPMQgfCSsIDyU0ENzE7PTsEO727hE5ERI5"
    "MQAQ5DL0POTsEO727hDuMEtTWAcQBe0HEAXtWSIBIgYVFBYzMjY1NCYnMhYVFAYjIiY1NDYBIwEzITIWFRQGIyImNTQ2FyIGFRQW"
    "MzI2NTQmBjNHTk1ISExNR7rW1rq619f9Jd0Dpd77jbrV1bq61dW6SE5OSEhNTgJoe3Jze3tzcnuo2L2929u9vNn80wYN2b292tq9"
    "vdmofHJzfX1zcnwAAAIAe//jBqQF8AAmADABNkBZDAENCw8JCAoPCAkILC0uLwQrMA8BAQAoASknDwABACUwJwgBBAQLLQkUAAQe"
    "kR0toQ4hnx2eGpwOmAQJJyoAJAEdCAUECzAkHRQqJA0dFwQBBQkXKg0RDDEQ/OzE1NTsEMbuEjkREjk5ERI5EjkRORI5MQAvxuT2"
    "5u4Q7hDuETk5ERI5ERc5MEtTWAcQDu0RFzkHEA7tERc5BxAF7QcF7REXOVkisggnAQBdQIQGAA8DDwQJCQ8KDgsJJwswFgAfAx8E"
    "GQkdCh0LHDAlAC8KLwslJj8KPwtAB0sKSwtLL0swWgFaAlUHWgpaC1UoXC5cMFgyXzJkAGkCZwdgB2kKaQtkJoAyLAkLCicZCxon"
    "Kgs5CzUcMB0wHjUfQAJKC0knSShXAVcCXAtbJ2cCZwdsCxVdAV0JAT4BNyEGAgcBIScOASMgADU0NjcuATU0NjMyFhcRLgEjIgYV"
    "FBYDDgEVFBYzMjY3Ax8BmTU3BQE3D29jASX+WGJp6IL++f67j6IqKP7TW8VrXqhQTVUxl0FCqndDdDID3/4+Rq5utv7ka/6+bUZE"
    "ARXbkuFqNWo6o8QdHf7qMC47NiJX/tMvd0dzoikpAAEAwwOqAbAF1QADABVACgGOAI0EAAQCAwQQ/OwxABD07DABESMRAbDtBdX9"
    "1QIrAAEAsP7yAwQGEgANAB9ADwCkB6MOBwEECAALEQQQDhD8/MQyEjk5MQAQ/OwwASEmAjU0EjchBgIVFBIDBP7XmZKTmAEpgIB/"
    "/vL3Ab3b2wHB9e3+O93d/joAAAEApP7yAvgGEgANABxADQCkBqMODQcKEQYAAw4Q1MQy7Dk5MQAQ/OwwEzYSNTQCJyEWEhUUAgek"
    "gICAgAEpmJOSmf7y7gHG3d0Bxe31/j/b2/5D9wAAAQApAjkEBgXwABEARkAoEA0LCgkHBAIBAAoMCAMFpREMDpwSCAwKAwkGEQMB"
    "AwIADwQLCQ0GEhDUPMQy3DzEMhc5ERIXOTEAEPTEMvTEMhEXOTABDQEHJREjEQUnLQE3BREzESUEBv62AUpM/rOq/rJMAU7+skwB"
    "TqoBTQTBra6NuP6oAVi4ja6tjbYBWP6otgABANkAAAXbBQQACwAiQBAABwOnCQGmBQgEABICCgYMENQ8xPw8xDEAL/Q8/DzEMAER"
    "IRUhESMRITUhEQPRAgr99u799gIKBQT99Oz99AIM7AIMAAABAG3+3QI5AYMABQAZQAwDqQCoBgMEAQIAEwYQ/OzUzDEAEPzsMBMh"
    "EQMjE9EBaPfVZAGD/s/+iwF1AAABAG8BvALjAt8AAwAStwKrAKoEAQAEENTEMQAQ9OwwEyERIW8CdP2MAt/+3QAAAQDRAAACOQGD"
    "AAMAEbcAqAIBAgATBBD87DEAL+wwEyERIdEBaP6YAYP+fQABAAD/QgLsBdUAAwATtwIAjQQCAAEDL8Q5OTEAEPTMMAEzASMCDt79"
    "8d0F1fltAAACAGL/4wUvBfAACwAXACNAEwmsDwOsFZwPmBgAFgwXBhYSFBgQ/Oz87DEAEOT07BDuMAEQJiMiBhEQFjMyNgEQACEg"
    "ABEQACEgAAOuaXx8amp8e2oBgf7A/tr+2f7AAUABJwEmAUAC7AEY5eX+6P7l6OgBGP6N/m0BkwFzAXQBk/5tAAABAOcAAAUEBdUA"
    "CgAoQBUDrgQCrgWNBwCuCQgYBhoDABgFAQsQ1MTsxPzsMQAv7DL07NTsMBMhEQURJSERIREh8AFU/qMBWwFuAVT77AEKA8VIAQZI"
    "+zX+9gABAKIAAATfBfAAGACLQCkAHQQFBBcBFhgdBQUEJQUYAA6QDwusEpwEAK8CGBUFAA4IFhUBGw4DGRDcS7ANVFi5AAP/wDhZ"
    "xPzU7BE5ORE5MQAv7DL07NTsETk5MEtTWAcQDu0RFzkHEAXtWSIBQCYCFyoWKhcDAwAOFwUYFxcXGCIAIhciGDUANRc1GEIASgVG"
    "F0YYD10AXQEhESERAT4BNTQmIyIGBxE+ATMgBBUUBgcCTgKR+8MCIUlGjXVa1nqC/noBDAEpfsoBG/7lARsB4UJ+RGmATUwBSCst"
    "7NN607EAAQCJ/+ME7gXwACgATEArABWsEwmWCrENrAYglh+xHKwTsCOcBpgpFhMZFAAQGRYmEBYDHxQfIAkeKRD85MT87NTsEjkR"
    "Ejk5MQAQ5PTk/PTsEP717hDuOTABHgEVFAQhIiYnER4BMzI2NTQmKwE1MzI2NTQmIyIGBxE+ATMgBBUUBgO6l53+rP66c+dxbNVn"
    "maOno5qikY6Kfl2+XnLgbAEjASGKAyUnwZXe5yUlASk2N2pjZmn4W11WXiopARogIL/Ag6cAAgBcAAAFMwXVAAIADQBDQCABIQ0D"
    "DQAhAwMNJQADCweuBQEDjQkBDAoAGgYIBAwUDhD81DzE7DIROTEAL+TUPOwyEjkwS1NYBxAE7QcQBe1ZIgkBIQMhETMRIxEhESER"
    "AvL+WgGmQAGs1dX+lP1qBJj9jwOu/FL+6f7wARABSgABAJ7/4wUCBdUAHQA9QCIEBx2VGqwHEJYRlRSsB7INAq8AjQ2YHgMiAAEX"
    "FgofABAeENzE/OzEEO4xABDk9OwQ5v717hD+5BI5MBMhESEVPgEzIAAVFAAhIiYnER4BMzI2NTQmIyIGB9kDvf12LFkwAREBMP61"
    "/tp/+Xt622GMoaGMU7xsBdX+5ecMDf7v9PL+7jEyAS9GRol1dogrLQAAAgB//+MFIwXuAAsAJAA3QB8TAKwWBqwcDJYNlRCsIpwc"
    "mCUMCRoZAyUTGhkXHyQlEPzs/OQQ7sQxABDk9Pz07BDu1u45MAEiBhUUFjMyNjU0JgERLgEjIgYHPgEzMgAVFAAhIAAREAAhMhYC"
    "5WVlZWVmZWUBdl+oUKzAEEKaW+UBGf7G/vj+3f7BAXUBRWfCAuGDg4ODg4ODgwLN/uwtK7+8MTH+9Nnw/t8BiQFpAXIBpyAAAQCJ"
    "AAAE7gXVAAYARUAXBRkCAwIEGQMDAiUFrwCNAwUEAwMBAAcQ3MwXOTEAL/TsMEtTWAcQBe0HEAXtWSKyBwMBAV1ACwcDGgUmAzUD"
    "RgMFXRMhFQEhASGJBGX9uv6JAif9MQXV2fsEBLoAAwB9/+MFEgXwAAsAIwAvAEdAKBgMJ6wABqweALAtrBKcHpgwGBUJDAMkGg8q"
    "GhUmCRobJwMaDyYhJDAQ/OTs/Oz07BDuEjkREjkxABDk9OzkEO4Q7jk5MAEiBhUUFjMyNjU0JiUuATU0JCEgBBUUBgceARUUBCEg"
    "JDU0NhMUFjMyNjU0JiMiBgLJbHR0bGtycv58iIoBGgERAQ8BGouImJv+2f7e/t3+15vyY1xaYmJaXGMCnHZubnV1bm91fymqf73G"
    "xb5/qikqvZDe4+PekL0BVVlgYFlZX2AAAAIAav/jBQ4F7gAYACQAN0AfBxmsCgCWAZUErBYKH6wQnBaYJRwlBxoTFwAiGg0kJRD8"
    "7MT8/OQxABDk9OzEEP717hDuOTA3ER4BMzI2Nw4BIyIANTQAISAAERAAISImATI2NTQmIyIGFRQWzVyoUqzAEUSaWuX+5wE5AQcB"
    "JAFA/or+umnAAX9lZmZlZWZmIQEUKyu/vDIyAQva8QEi/nb+mP6O/lkfAu6Dg4KEhIKDgwACAOUAAAJOBGAAAwAHABxADgKoALME"
    "qAYFAQIEABMIEPw87DIxAC/s9OwwEyERIREhESHlAWn+lwFp/pcEYP59/qb+fQAAAgCB/t0CTgRgAAUACQAlQBMIqAYDqQCoBrMK"
    "AwQHAQIGABMKEPw87DLUxDEAEOT87BDuMBMhEQMjExEhESHlAWn41WQBaf6XAYP+z/6LAXUEDv59AAABANkAPQXbBMcABgAfQBAF"
    "BAIBAAUDtQa0BwECAAQHENTEMjkxABD07Bc5MAkCFQE1AQXb/DwDxPr+BQIDzf60/rb6Ac/sAc8AAAIA2QEnBdsD2wADAAcAHEAN"
    "AKcCtganBAgFAQQACBDUPMQyMQAQ1Oz87DATIRUhFSEVIdkFAvr+BQL6/gPb69ztAAEA2QA9BdsExwAGAB9AEAYFAwIABQS1AbQH"
    "BgIEAAcQ1DzEOTEAEPTsFzkwEzUBFQE1AdkFAvr+A8UDzfr+Mez+MfoBSgACAI0AAAQfBfAAHQAhAEhAJx0aBQIEBhkPAIweEJEP"
    "lQyhE40eiyAGBQkBGhkACQIWDx8AAh4BIhDUPOwy1NTsEjk5ERI5OTEAL+z0/PTsEO0ROTkXOTABITU0Nj8BPgE1NCYjIgYHET4B"
    "MzIEFRQGDwEOARUFIREhAsX+l0JqQDk1YFZRvGZ5yF30AQBOXkBEKv6XAWn+lwH4MVJ/Yjo0XC5GT0NCAToqKMe/YptZOT5LLcH+"
    "nAAAAgCH/pwHbwWgAAsATQBsQDoMDwM0MExNMw8YGQkbA7gPMzAJuBkVMLgPtzckuBW3Q49OMzRMGgYYDCoaACoSHikaKEkSKCop"
    "ND1OENTE7OzU7OwQ7hD+PMYSORE5MQAQ9Ozs1OzsEMTuEMQQ7jIREjkREjk5ETkREjkwARQWMzI2NTQmIyIGAQ4BIyImNTQ2MzIW"
    "FzUzET4BNTQmJyYkIyIGBwYCFRQSFxYEMzI2NxcGBCMiJCcmAjU0Ejc2JDMyBBceARUQACEjAz9pWllqa1pYaQGaHoVZrNfYq1mF"
    "HtF8jjo7X/7jpnTUWpSla2VkAQOTfvxZa33+2Zi5/riAgIaIfn4BT7TgAW57S03+uv7XJwIbe46PenmNjf5aR0/5yMj6UEeD/UsT"
    "yZ1kr0l6hD07Yv7JtZX++2RiZ15QomFng319AUm9tgFKfXyIq6Fi5X7+8f7UAAACAAoAAAYnBdUABwAKAP5AQAAdBgUHHQYGBQod"
    "CAoFBgUJHQYGBQIdBAMBHQQDCB0DBAMKHQkKBAQDJQoEAK4IBI0GAgoJCAcFBAIBAAkGAwsQ1LIfAwFdxBc5MQAvPOTU7BI5MEtT"
    "WAcQCO0HEAXtBwXtBwXtBxAF7QcQCO0HEAXtBwXtWSIBQIAYCi8KVgpmCn8AfwF/CH8JdAqKCp8Kvwq/Cs8KzwrfChASCBwJHwwl"
    "CCoJIAxJBEYFRwhICVgDWQRWBVcGaANpBGYFZwZgDHQAewF6BHUFewh0CYkEhgWGCIkJmQSWBZUImgm2CLkJywDFAcUCywfCCM0J"
    "2QDWAdYC2QfVCNoJL10AXQEhAyEBIQEhASEDBEb9pl/+fQIpAcsCKf59/agBmcwBEP7wBdX6KwIlAlIAAAMAvAAABYkF1QAIABEA"
    "IABQQCUSALkPvga5Go0JuRgGAAcDEh4MDwkYGwQHAxYeDBYVEAcWGQMhEPzsMtTs1OwRFzkREjkREjk5MQAv7PTs9Ow5MEAJACIQ"
    "Ii8iUCIEAV0BMjY1NCYrARETMjY1NCYrAREBHgEVFAQpAREhIAQVFAYDElteXlvV4nR1dHXiAkh8iP7c/tb9gQJCATcBF2YDk1BO"
    "TVH+xP1zYmNhYf55Ahkkwo3Y1AXVvM9tmQABAGb/4wVcBfAAGQA7QBoMEAkAFgMNEBkWrgMQrgmcA5gaEy0MAAYrGhD8xDLsMQAQ"
    "5PTsEP7EEMUREjkREjkwtC8bXxsCAV0lDgEjIAAREAAhMhYXES4BIyICFRQSMzI2NwVcauZ9/ov+TAG0AXV95mpr0HPO7OzOc9Br"
    "Ujc4AaEBZQFmAaE4N/7LSUT++Ojn/vhESQACALwAAAY5BdUACAAXAC5AFQDACY0BwBYIAhYKAAUtEC4AFgkDGBD87PzsETk5OTkx"
    "AC/s9OwwslAZAQFdAREzMjY1NCYjASEgBBcWEhUUAgcGBCkBAj2K7Pn47f31AZYBVAFNd2lmZml4/rD+sP5qBLL8cerf3ugBI2F0"
    "Zf74p6n+92V0YQAAAQC8AAAE4QXVAAsAMEAUBMAGvgLAAI0IwAoBBQkHAxYAAwwQ/Owy1MTEMQAv7PTs9OwwthANUA1wDQMBXRMh"
    "ESERIREhESERIbwED/1yAmf9mQKk+9sF1f7d/ur+3f6q/t0AAAEAvAAABMsF1QAJACtAEQTABr4CwACNCAUBBwMWAAMKEPzsMtTE"
    "MQAv9Oz07DC2EAtQC3ALAwFdEyERIREhESERIbwED/1yAmf9mf5/BdX+3f7q/t39hwABAGb/4wX6BfAAHQBLQCUZGhYMEAkAFgMN"
    "EBq5HBauAxCuCZwDmBweGxkxDDMALxMtBiseEPzs9OT8xDEAEMTk9OwQ7hDuEMUREjkREjkREjkwsl8fAQFdJQYEIyAAERAAITIE"
    "FxEuASMiAhUUEjMyNjcRIxEhBfqQ/sql/ov+TAG8AYKVARF5ffd85vnw3TxnKesCWG9GRgGhAWUBaQGeODf+y0dG/v/v7f7+DxAB"
    "IgECAAABALwAAAX2BdUACwA+QBMCwAi+BACNCgYHAxYFCQEWAAMMEPzsMtTsMjEALzz0PPTsMEAVDwMPBA8FDwYPBw8IUA1gDXAN"
    "nw0KAV0TIREhESERIREhESG8AYECOAGB/n/9yP5/BdX9xwI5+isCef2HAAABALwAAAI9BdUAAwAstwDBAgEWAAMEEPxLsA9US7AQ"
    "VFtYuQAAAEA4WewxAC/sMAG2EAVABVAFA10TIREhvAGB/n8F1forAAAB/43+ZgI9BdUACwBBQBMLAgAHwAXCAI0MBQgGARYGAAMM"
    "EPxLsA9US7AQVFtYuQAAAEA4WcTsEjk5MQAQ5PzsETk5MAG2EA1ADVANA10TIREQACEjETMyNjW8AYH+0f7NTjx4ewXV+rz+6f7s"
    "ASOGggABALwAAAZxBdUACgCBQBMIBQIDAwDBCQYFAQQGCAEWAAMLEPzsMtTEETkxAC887DIXOTBAVhYFFgYQDDwDOwdMA0sHWwNY"
    "BV0HbwNnBWcGYAZoB2AMfwN4B38HcAyFBIYGqgcXJwIyAjsIQgJLCFQCWQVYCF8IYAJmBW0IcAJ4BXsIfwiKBY0IqwgTXQFdEyER"
    "ASEJASEBESG8AYECKwG//TEDGf4e/a7+fwXV/d8CIf09/O4CTP20AAABALwAAAThBdUABQAXQAsCwACNBAEWAwADBhD8xOwxAC/k"
    "7DATIREhESG8AYECpPvbBdX7Tv7dAAEAvAAABzkF1QAMAM5AMwM2BwgHAjYBAggIBwI2AwIJCgkBNgoKCSUKBwIDAAgDAMELBQkI"
    "AwIBBQoGMQQKMQADDRD87NTsERc5MQAvPOwyxBEXOTBLU1gHEAXtBxAI7QcQCO0HEAXtWSKyDwMBAV1AZgkCDwgPCR8CFQcfCB8J"
    "FQorAj8CSAJPAkwHTApXAlkHWQpoAm8HbwqVApAIkAmpArAHsAoaBAEEAwAOFgEZAxAOKgElAzoBNQNPAUADRwhWCFkJUA5oAWcD"
    "ZQhqCWAOhQiKCZcIGF0AXRMhCQEhESERASMBESG8AeoBVAFWAen+lP6o9P6o/pMF1fzhAx/6KwRE/NsDJfu8AAABALwAAAX2BdUA"
    "CQB8QB0HNgECAQI2BgcGJQcCAwDBCAUGAQcCMQQHMQADChD87NTsETk5MQAvPOwyOTkwS1NYBxAE7QcQBO1ZIrIPBwEAXUA0CgYA"
    "CxkGOAFHAUoGVgFZBlALZwFoBmALugG2Bg4ZAhoHPgIzB0kCTwJAB1UCWgdmAmkHC10BXRMhAREhESEBESG8Aa4CHwFt/lL94f6T"
    "BdX8AAQA+isEAPwAAAACAGb/4wZmBfAACwAXADJAEwauEgCuDJwSmBgJLQ83Ay0VKxgQ/Oz87DEAEOT07BDuMEALABkXExAZLxk/"
    "GQUBXQEiAhUUEjMyEjU0AgMgABEQACEgABEQAANmsMLCsLHCwrEBaAGY/mj+mP6Z/mcBmQTZ/vzs6/78AQTr7AEEARf+ZP6V/pb+"
    "ZAGcAWoBawGcAAIAvAAABYkF1QAKABMAMUAWDK4HC64AjQkTDQcBCBAtBAsIFgADFBD87DLU7BE5OTk5MQAv9OzU7DCyABUBAV0T"
    "ISAEFRQEISMRIQERMzI2NTQmI7wCfwEdATH+z/7j/v5/AYHVcHp6cAXV/err/f36BL7+X21kZGwAAgBm/tUGZgXwAA8AGwBiQBoN"
    "Fq4AEK4HnACYDhwOCgENExktCjcTLQQrHBD87PzsETk5ETkxABDE5PTsEO45MEAsCAwAHRkMEB0nAC8dVgxTDWYMYA13DHcNcA0N"
    "BwxZC1kNWRRYGGoLaQ14DAhdAV0FIyAAERAAISAAERQCBwEhASICFRQWMzISNTQCA48e/o/+ZgGZAWcBawGV18oBLf6R/uOwwr60"
    "scLCGwGYAWwBawGc/mj+kfz+lFz+sAYE/vzs8P8BBOvsAQQAAgC8AAAGAAXVAAgAHACHQDIbGgIcGR0WFxYYHRcXFiUZFgoTAK4J"
    "Bq4MjRcKFhMYAxAcGQYABA0HAxYXEAkHFgsDHRD87DLUxOwRORc5ERc5MQAvPPTs1Ow5Ejk5MEtTWAcQBe0HEAXtERc5WSKyGBwB"
    "AV1AHxsYGxkaGhsbGhw2FTYWRRVFFlYVVhZQHmUVZRZgHg9dATI2NTQmKwEZAiERISAEFRQGBx4BFxMhAy4BIwLfeWlpeaL+fwJM"
    "AScBE4+QT31A0f5mtjdxXgM/WmdmWP6B/vb9ywXVxtaUvi0Sf4H+WAFzcFIAAQCT/+MFLQXwACcAp0AqACUEFBgRCgseHwQVAcME"
    "FcMYrhEEriWcEZgoHgoLHxsHABsZDhQHGSIoENzsxNTsxBESOTk5OTEAEOT07BD+5RDlERc5ERI5ERI5MEBUcCkBOR05HjkfOSBK"
    "HkofSiBYCl0dXB5eH14gWiFqHG8dbx5vH2ggbyBuIXQLdAx0DXwffCB8IZYLlwybHpofnCCaIaYLpgymDaodqh6qH6ogqiEoXQFd"
    "AREuASMiBhUUFh8BHgEVFAQhIiQnERYEMzI2NTQmLwEuATU0JCEyBATLe+poioRZdaT50v7b/tOO/uKPjwELfH6GW4iV4M8BIAEO"
    "ewEEBab+xDc4TFA8QxghMsy89/E2NQFFTE1UTkZMHiEw0rLf8CUAAQAKAAAFagXVAAcAM0AOBgLAAI0EATgDFgA4BQgQ1EuwClRL"
    "sA5UW1i5AAUAQDhZ7PzsMQAv9OwyMAGyQAkBXRMhESERIREhCgVg/hH+f/4QBdX+3ftOBLIAAQC8/+MFwwXVABEAM0AXEQsIAgQA"
    "BcAOmAkAjRIIFgo5ARYAAxIQ/Oz87DEAEOQy9OwRFzkwtkATcBOfEwMBXRMhERQWMzI2NREhERAAISAAEbwBgXmJinkBgf7C/rr+"
    "u/7CBdX8gbmfn7kDf/yB/sP+ygE2AT0AAQAKAAAGJwXVAAYAg0AnAx0EBQQCHQECBQUEAh0AAgYABgEdAAAGJQIDAMEFBgUDAgEF"
    "BAAHENS0jwAfAAJdxBc5MQAv7DI5MEtTWAcQBe0HEAjtBxAI7QcQBe1ZIgFALAACEAIgArACBAcBCAMXARgDGAQXBR8IIAhHAEcB"
    "SANIBEUFSgZXAVgDjwgRXQBdEyEJASEBIQoBgwGMAYsBg/3X/jUF1fuyBE76KwAAAQA9AAAIkwXVAAwBbUBKBh0HCAcFHQQFCAgH"
    "CjYLCgQFBAk2BQUECzYCAwIKNgkKAwMCAh0DAgwADAEdAAAMJQoFAgMGAwDBCwgMCwoJCAYFBAMCAQsHAA0Q1EuwCVRLsApUW0uw"
    "C1RbS7AMVFtYuQAAAEA4WcwXOTEALzzsMjIXOTBLU1gHEAXtBxAI7QcQCO0HEAXtBxAF7QcQCO0HEAjtBxAF7VkiAUDMAwoVAhAC"
    "FAUQBRAKJQogCiAKOgI/AjoFPwUzCjAKMApACkAKQApeAl4FYQq4ArEKsAqwChoFAgoFCQgJCQULBgwWAhgDFwQZBRUIFAkaCxoM"
    "JwIoAycEKAUlCCoMLw42AjYDMgQyBTAGMAcwCDIJNAo2Cz8OSQNGBEgFRQlKC10AXQFaAloDVQRVBVIGUgdSCFoJVQtdDG8AbwFv"
    "Am4DaARoB2UIaAlrCm4LaQxvDHcDdwh4CXYLeAyIB4UIiQy3AroDtgS4BbEIvgxLXQBdEyEJASEJASEBIQkBIT0BcQECAQABcwEA"
    "AQIBbv6g/kT+8f70/kQF1fvDBD37wwQ9+isEb/uRAAABACcAAAYCBdUACwDwQEUEHQUGBQMdAgMGBgUKHQsACwkdCAkAAAsJHQoJ"
    "BgcGCB0HBwYDHQQDAAEAAh0BACUJBgMABAoHwQQBCQYDAAQHCwEHBQwQ1EuwClRLsA9UW0uwEVRbWLkABQBAOFnE3MQRFzkxAC88"
    "7DIXOTBLU1gHBe0HEAjtBxAF7QcQCO0HEAjtBxAF7QcQCO0HEAXtWSIBQFgIAw8DBgkACR8DEAkvAyYJIAk8AzMJXwNQCY8DgAm/"
    "A7AJEQkCBgQGCAkKGwIUBBQIGworACsCJQQkBiUIKwo6AjUENQg6ClANZQBqBm8NuQK1BLUIugoaXQBdCQEhCQEhCQEhCQEhA/wC"
    "Bv5v/qP+pv5tAgb+DgGSAUcBRgGUAvr9BgH+/gIC+gLb/h8B4QAB/+wAAAXfBdUACACVQCgDHQQFBAIdAQIFBQQCHQMCCAAIAR0A"
    "AAglAgMAwQYCBwQ6BRYAOgcJENRLsAlUS7ANVFtLsA9UW1i5AAcAQDhZ7PzsEjkxAC/sMjkwS1NYBxAF7QcQCO0HEAjtBxAF7Vki"
    "AUAsAAIQAiACJQUlCDACQAJQAmACsAIKCgAFBBUBGgMlASoDNQE6AzAKTwpvCgtdAF0DIQkBIQERIREUAaUBVAFUAab9x/5/BdX9"
    "7AIU/KD9iwJ1AAABAFwAAAVxBdUACQBiQBoDHQcIBwgdAgMCJQjAAI0DwAUIAwABBAAGChDUtB8GDwYCXcTcxBE5OTEAL+z07DBL"
    "U1gHEAXtBxAF7VkiAUAfBQMLCBUDGgglAykINgM5CD8LRgNICE8LVgNfC28LD10TIRUBIREhNQEhcwTn/N8DOPrrAyH89gXV6fw3"
    "/t3pA8kAAAEAsP7yAx0GFAAHAB9AEATEBqQCxACjCAUBAxEAEAgQ/PzMMjEAEPzs/OwwEyEVIREhFSGwAm3+5wEZ/ZMGFOH6oOEA"
    "AQAA/0IC7AXVAAMAE7cAAY0EAgADAS/EOTkxABD0zDAFATMBAg798t0CD74Gk/ltAAABAIv+8gL4BhQABwAeQA8CxACkBMQGowgA"
    "EQUBAwgQ1Mwy7DEAEPzs/OwwASE1IREhNSEC+P2TARn+5wJt/vLhBWDhAAEAzwOoBeUF1QAGABhACgMEAQCNBwMBBQcQ1Mw5MQAQ"
    "9MwyOTAJASMJASMBA9UCEPH+Zv5n8gIQBdX90wEt/tMCLQAAAQAA/h0EAP7bAAMADrQAAQQAAi/EMQAQ1MwwARUhNQQA/AD+276+"
    "AAEAXgTuApMGZgADAE63AcYAxQQBAwQQ1MwxABD07DAAS7AJVEuwDlRbWL0ABP/AAAEABAAEAEA4ETc4WQFLsAlUWL0ABP/AAAEA"
    "BAAEAEA4ETc4WbQaAhoDAl0JASMBAXkBGsT+jwZm/ogBeAAAAgBY/+MExQR7AAoAJQCdQCoJBgAZHwsA0hfPBp8O0BEgzB/LHJ8j"
    "yhGYDAAjFwMYDQkNCz0fAw0UOyYQ/OzE9OwyMhE5OTkxAC/k9Pz07BDm7vbuORI5ERI5MEBMLyc9ID0hPydNIE0hXSBdIW4gbiF+"
    "IH4hcCeMIIwhnSCdIa0grSG9IL0hFTIeMB9DHkAfUx5QH2MeYB+FHoAfkx6QH6IeoB+yHrAfEF0BXQEiBhUUFjMyNj0BJREhNQ4B"
    "IyImNTQkITM1NCYjIgYHET4BMyAEAqJwcVtRZYoBaf6XSLSBrtkBDwEi04aOc8ZVc+h0AS8BDQH4TEpETZFtKYf9gaZmXcuixbgc"
    "VU8uLgERHB3vAAIArP/jBV4GFAALABwAOEAbBqEM0A8AoRWYD8oboxjQGQNCEkAYDAkNGhAdEPzsMjL07DEAL+Ts5PTsEObuMLRP"
    "HmAeAgFdJTI2NTQmIyIGFRQWAz4BMzIAERAAIyImJxUhESEDAHN5eXNze3t7SrR1zwEK/vbPdbRK/poBZueooKCoqZ+fqQLVYl3+"
    "t/79/v3+t11iogYUAAABAFj/4wQ1BHsAGQA3QBoAzAHUBA7MDdQKoREEoRfKEZgaB0INABQ7GhD8xDLsMQAQ5PTsEP707hD17jC0"
    "Xxt/GwIBXQERLgEjIgYVFBYzMjY3EQ4BIyAAERAAITIWBDVJk0+Wp6eWVJdAVK1X/tH+qgFWAS9YqwQ9/twyMK+dna8yMf7bHx8B"
    "NwEVARUBNx8AAAIAXP/jBQ4GFAAQABwAOEAbF6EA0A4RoQXQCJgOygGjAxQEAA0CQBpCCzsdEPzs9OwyMjEAL+zk9OTsEOTuMLRP"
    "HmAeAgFdAREhESE1DgEjIgAREAAzMhYDMjY1NCYjIgYVFBYDpgFo/phKsnXP/vYBCs90s6JzeXlzcnl5A7wCWPnsomNcAUkBAwED"
    "AUld/MmooKCoqKCgqAACAFj/4wUKBHsAFAAbAENAIQAV2AEJzAjUBZ8MAdcYnxLKDJgcGxUCCBUNAEQCDQ87HBD87PTsxBESOTEA"
    "EOT07OQQ/vTuEO45MLQvHT8dAgFdARUhHgEzMjY3EQ4BIyAAERAAISAABTQmIyIGBwUK/LsNnIxx7X1//n/+0P6vAUsBIgEIAT3+"
    "kHdgaIIQAjNmfn5DRP7sMDEBNQEXARIBOv7Ck2Z9dW4AAAEAJwAAA40GFAATAFFAHBAFAQwIoQYBnwCjDgazCgITBwAHCQUNDUUP"
    "CxQQ3EuwDVRLsA5UW1i5AAsAQDhZPOz8PMTEEjk5MQAv5DL87BDuMhI5OTABQAWAB4AIAl0BFSMiBh0BIREhESERIxEzNTQ2MwON"
    "xkw8ATL+zv6asrLM1gYU6zdETv8A/KADYAEATrevAAACAFz+RgUOBHkAHAAoAEtAJhwPAwAVzBbUGZ8SHaEM0AnKDbMjoRLaANAD"
    "JgwADQ5AFSBCBjspEPzsxPTsMjIxAC/k5Ozk9OTsEP717hESOTkwtE8qYCoCAV0lDgEjIgA1NAAzMhYXNSEREAAhIiYnER4BMzI2"
    "NQMiBhUUFjMyNjU0JgOmSrJ1zf70AQzNdbJKAWj+q/68acRjXrRbsKTsb3x4c3B8fL5iXAFD+vsBQVxjpvwR/vL+4yAhARc2NZqk"
    "AwaklpqfpJWWpAABAKwAAAUSBhQAFwA1QBgNBAABCtsS0BXKEKMOAQINAEcRDQ0PEBgQ/Owy9OwxAC887PTk7BE5OTkwtGAZgBkC"
    "AV0BESE1ETQmJy4BIyIGFREhESERPgEzMhYFEv6YDRAVSC5wgP6aAWZRtm7CyQKq/VZvAZmTbhojJ62Z/dkGFP2oYl3uAAIArAAA"
    "AhIGFAADAAcAKUAOBt0AswSjAgUBDQQAEAgQ/DzsMjEAL+z07DBACVAJYAlwCYAJBAFdEyERIREhESGsAWb+mgFm/poEYPugBhT+"
    "3AAC/7z+RgISBhQACwAPAD1AGQsCAAefBQ7dALMF2gyjEAUIBg0BDQwAEBAQ/DzsMsQ5OTEAEOzk9OwQ7hE5OTBACVARYBFwEYAR"
    "BAFdEyERFAYrATUzMjY1ESERIawBZtjNsT5mTAFm/poEYPu04e3rXIcGAP7cAAABAKwAAAV5BhQACgCMQBQIBQIDA7MAowkGBQEE"
    "BggBDQAQCxD87DLUxBE5MQAvPOzkFzkwQGAZAxkEGQUZBjsHSQNJB1oDXQZYB18HbwNnBX8DdgR2BnsHiAOFBIcFiwefA5UFlgab"
    "B7kDGhYCFgU6CEQCRwVKCFYCXQhnAmACZQV3AnACdgV8CIcCiAWLCJIClwWbCBVdAV0TIREBIQkBIQERIawBZgGcAaD93QJO/k7+"
    "S/6aBhT8sQGb/f79ogHT/i0AAQCsAAACEgYUAAMAHrcAowIBDQAQBBD87DEAL+wwQAlQBWAFcAWABQQBXRMhESGsAWb+mgYU+ewA"
    "AAEAqgAAB7QEewAlAGlAKRsVEgkEBwAgBgcYD9sg0CMDyh6zHBMHABQSDAgNBkgUDRJIHxsNHRAmEPxLsA9UWLkAHQBAOFn8PPzs"
    "/Ow5ERI5MQAvPDzk9Dzk7DIRORE5ERc5MAFADx8nMCdQJ3AngCeQJ68nB10BPgEzMhYVESERPgE1NCYjIgYHESERNCYjIgYVESER"
    "IRU+ATMyFgS6RLtwwcr+mAEBRk5mbwL+mEBSZ3D+mAFoQqtndLIDpmht7uP9VgJIDRwad2uon/3aAki6a6md/dkEYKRfYHAAAAEA"
    "rAAABRIEewAXADVAGA0EAAEK2xLQFcoQsw4BAg0ARxENDQ8QGBD87DL07DEALzzk9OTsETk5OTC0YBmAGQIBXQERITURNCYnLgEj"
    "IgYVESERIRU+ATMyFgUS/pgNEBVILnCA/poBZlG2bsLJAqr9Vm8Bm5FuGiMnrZn92QRgpGJd7gAAAgBY/+MFJwR7AAsAFwAtQBMG"
    "oRIAoQzKEpgYCUIPTANCFTsYEPzs/OwxABDk9OwQ7jC2NxM/GUcTAwFdASIGFRQWMzI2NTQmAyAAERAAISAAERAAAsF3fX13dXx8"
    "dQEhAUX+u/7f/t7+uQFHA3uroaGrq6GhqwEA/sj+7P7s/sgBOAEUARQBOAAAAgCs/lYFXgR7ABAAHAA7QB0XoQDQDhGhBdAIyg6Y"
    "Ad4Dsx0aQgtAFAQADQIQHRD87DIy9OwxABDk5OT05OwQ5O4wtE8eYB4CAV0lESERIRU+ATMyABEQACMiJhMiBhUUFjMyNjU0JgIS"
    "/poBZkq0dc8BCv72z3W0pHN7e3NzeXmi/bQGCqRiXf63/v3+/f63XQM3qZ+fqaigoKgAAgBc/lYFDgR5AAsAHAA7QB0GoQzQDwCh"
    "GNAVyhmzG94PmB0YDAkNGkADQhI7HRD87PTsMjIxABDk5OT05OwQ5u4wtE8eYB4CAV0BIgYVFBYzMjY1NCYTDgEjIgAREAAzMhYX"
    "NSERIQK6cnl5cnN5eXlKsnXP/vYBCs91skoBaP6YA3eooKCoqKCgqP0rY1wBSQEDAQMBR1xjpvn2AAABAKwAAAPsBHsAEQA3QBYR"
    "DgkGBwADwAuUDsoJswcKBg0ACBASEPxLsBNUWLkACP/AOFnE7DIxAC/k9OT8xBE5ERI5MAEuASMiBhURIREhFT4BMzIWFwPsL10v"
    "ipX+mgFmRbN9EiooAy8WFbGl/fwEYLhuZQMFAAABAGr/4wRiBHsAJwDcQEANDAIOCzYeHx4FBgcICQUECjYfHx4lCgseHwQVAMwB"
    "1AQUzBXUGJ8RBJ8lyhGYKB4KCx8bBwBTG1IOFAdQIk0oEPzsxNTs5BESOTk5OTEAEOT07BD+9e4Q9e4SFzkwS1NYBxAO7REXOQcQ"
    "Du0RFzlZIrIICwEBXUBeCQkJCgkLCwwLDQkPBSMaDBoNGg4YDywILgkuCi4LLgwuDSkgOQg7CTsKOws6DDoNSwlKCkoLSgxIDXcM"
    "dw26CLoJugq6C7oMug0lDgYOBw4IDgkOCg0LNw0/KV8pCV0AXQERLgEjIgYVFBYfAQQWFRQEISImJxEeATMyNjU0Ji8BLgE1NDYz"
    "MhYEF3PWX2ZjS2E/ARO+/vj++m/tfWvhdGlqSW0/78D0/GPaBD3+8DAwMzUrLgsJI6Crs7QjIwEQNDQ6OTAvDQgeoqWyrB4AAAEA"
    "GwAAA6QFngATAG1AGg4FCA8DoREBswihAAoICwkCCQQADRASDlQUEPxLsA9US7AQVFtLsBFUW0uwElRbWLkADgBAOFk8xPw8xMQS"
    "OTkxAC/E7PQ87DIROTkwAUAYPwA/EwIAAgADDxAPEVACUANQFWACYAMJXQBdAREhESERFBY7AREhIiY1ESMRMxECMwFx/o8+XLj+"
    "zdSxsrIFnv7C/wD+JU43/wCx1AHbAQABPgABAKD/4wUGBGAAGQA7QBsPAwABDNsU0BeYEAGzEgYCABMPDRFHAg0AEBoQ/Oz07DIR"
    "EjkxAC/kMvTk7BE5OTkwtGAbgBsCAV0TESEVFAIVFBYXHgEzMjY1ESERITUOASMiJqABaAIOERZHLnCAAWb+mlG1bcLLAbQCrHBb"
    "/u0uh3cbIyasmQIp+6CiYl3uAAABAB8AAAUZBGAABgDTQCcDHQQFBAIdAQIFBQQCHQMCBgAGAR0AAAYlAgMA3wUGBQMCAQUEAAcQ"
    "1LSfAB8AAl3EFzkxAC/sMjkwS1NYBxAF7QcQCO0HEAjtBxAF7VkiAUB8AAIAAhACEAIgAjACQAJWAmYCgAKQAqACsAKwArACsALA"
    "AsAC0ALQAuAC4ALgAvAC8AIZBQACAQ0DCgQVABMBHAMaBCYAJAErAykENgA0ATkDOQQwCEYARgFJA0kEYAh4BocBiAOHBYgGlgCW"
    "AZkDmQSVBZoGqAO2AbkDJF0AXRMhCQEhASEfAWYBFwEWAWf+R/53BGD8+gMG+6AAAAEASAAABx0EYAAMAYJASgYdBwgHBR0EBQgI"
    "Bwo0CwoEBQQJNAUFBAs0AgMCCjQJCgMDAgIdAwIMAAwBHQAADCUKBQIDBgMA3wsIDAsKCQgGBQQDAgELBwANENRLsApUS7ALVFtL"
    "sAxUW1i5AAAAQDhZzBc5MQAvPOwyMhc5MEtTWAcQBe0HEAjtBxAI7QcQBe0HEAXtBxAI7QcQCO0HEAXtWSIBQOYVCiAKNQI1BTAK"
    "RwpACkAKXwpsCn8KsAKwArAFsAWwCsACwAXRCtAK4ALgBe8KFxYCFAMUBBIFEAYQBxAIEgkUChYLJgEkAisFKQYqCCsJJAslDC8O"
    "NQA1ATQCOwU6BjoHNwg4DD8ORwJJA0YESAVHCEgMWQNWBFYIWwlUC1kMXw5mAmAEYgVgBmAHYAhkCmALdQJwBHMFcAZwB3AIdApw"
    "C4cBiAaECIkJhguLDI8OlAibDJAOpgKpA6YEqQWlCKkJpguqDLYBuQa2CLkMxgHEA8oEyQbVAtkD1wTaBeUI6QnmC+oMW10AXRMh"
    "GwEhGwEhASELASFIAVy8vQErvL0BXP7Z/nm9vP55BGD8/AME/QQC/PugAwL8/gABAB8AAAUKBGAACwF5QEYKHQsACwkdCAkAAAsJ"
    "HQoJBgcGCB0HBwYEHQUGBQMdAgMGBgUDHQQDAAEAAh0BAQAlCQYDAAQEAd8KBwkGAwAEAQUHAQsMENRLsApUS7APVFtLsBJUW0uw"
    "FFRbWLkACwBAOFnE1MQRFzkxAC887DIXOTBLU1gHEAXtBxAI7QcQCO0HEAXtBxAF7QcQCO0HEAjtBxAF7VkiAUDaAAMPCRADHwkg"
    "Ay8JMwM8CUMDTAlSA1wJYgNsCXMDegmBA4ADjQmPCZcAkAOQA5cGnAmfCaADrwmwA7ADsAO/Cb8JvwnAA8ADzwnPCdAD0APfCd8J"
    "4APgA+8J7wn3APAD9wb/CTIDAgwEDAgDChMCHAQcCBMKHw0kAisEKwgkCjQCOwQ7CDQKMA1EAksESwhECm8NhgCAAo8EiQaPCIAK"
    "lwCVApoEmQaaCJYKpwawAr8EvwiwCsACzwTPCMAK1wDQAt8E2AbfCNAK5wDgAu8E6AbvCOAK+QD2BjpdAF0JASEbASEJASELASEB"
    "x/5sAXvl6AF7/mwBqP6F/Pn+hQI9AiP+tAFM/d/9wQFi/p4AAAEAGf5GBRIEYAAPATZAQw8dAA8FBAsMDQMOHQUFBAMdBAUEAh0B"
    "AgUFBAIdAwIPAA8BHQAADyUOCgIQBQAKnwjaAwCzEA8OCwkIBQMCAQkEABAQ1EuwClRLsBJUW0uwFFRbWLkAAABAOFnEFzkxABDk"
    "MvTsETkSORE5MEtTWAcQBe0HEAjtBxAI7QcQBe0HEAXtFzkHCO1ZIgFApAACAAIQAhACIAJAAlACZQJ0AoYCgAKUApACoAK0ArAC"
    "sAKwAsACwALUAtAC4ALgAhgEAQkDBQUFBgUHBQgWARUFFQYVByQFJAYkBzUANQE4AzYGNgc5DjkPRQBFAUoDSgRFBUUGZwJlBoYC"
    "hgWGBogNiA6XApYFlgaZDZkOqAKqA6oEqQ6pD7UBvAO4BLAJsAq/C7kNuQ7IAssNyw7JD9YC5QI5XQBdEyEJASEBDgErATUzMjY/"
    "ARkBZgEtAQABZv4pR72bz3BbUxcKBGD9CAL4+za7les6Sx8AAQBcAAAERgRgAAkAiUAaCB0CAwIDHQcIByUIoQCzA6EFCAMABAEA"
    "BgoQ1LQfBg8GAl3EzDIROTkxAC/s9OwwS1NYBxAF7QcQBe1ZIgFARFkCVgdpAmYHeQJ2B4QHkwcIAAMPCBABEAIQAxAEEAUQCyYD"
    "KQgvCzkIPwtKCF8LjgieCLEDvQjAA88I0APfCOMD7AgZXQBdEyEVASERITUBIXUD0f2yAk78FgJO/csEYPr9mv8A+gJmAAEBAP6y"
    "BLIGFAAkAF5AMRkPFQsGJQkaEBUdCwUgIQMACcQL4QDEAeAVxBOjJR0ZDAkKBSQWEwIUACAZEQoPBSUQ1DzM/DzEMjk5OTkREjk5"
    "EjkxABD87PTs9OwRFzkRORI5ORESORESOTkwBRUjIiY9ATQmKwE1MzI2PQE0NjsBFSMiBh0BFAYHHgEdARQWMwSy2drIbI49PY5s"
    "yNrZRY1VWm5vWVWNbeGwwcCWdd90ls3Br+FXjqadjhkbjpymj1cAAQEE/h0B5wYdAAMAEbYBAAQABAIEENTsMQAQ1MwwAREjEQHn"
    "4wYd+AAIAAABAQD+sgSyBhQAJABgQDIfJRsWDA8IGwsVGQ8EBSADABvEGeEAxCPgD8QRoyUcGRoIFQ8BIxIEABofFREQAAsEJRDU"
    "PMwy/DzMERI5OTk5ETkSOTkxABD87PTs9OwRFzkREjk5ETkROTkREjkwBTMyNj0BNDY3LgE9ATQmKwE1MzIWHQEUFjsBFSMiBh0B"
    "FAYrAQEARoxVWm9vWlWMRtnayGyOPT2ObMja2W1Xj6acjhsZjp2mjlfhr8HNlnTfdZbAwbAAAQDZAbIF2wNSAB0AI0AQARAbDAAT"
    "BKcbDKcTHgAPHhDUxDEAENTs3OwQwBESOTkwARUOASMiJyYnJicmIyIGBzU+ATMyFxYXFhcWMzI2Bdtqs2Brjw4IBw+bXlisYmuy"
    "YGuPDwcHD5teVqkDUvRQRToGAwMGPU1T9FBFOgYDAwY9SwAAAQCsAAACEgYUAAMAABMhESGsAWb+mgYU+ewAAAEAnf4MBcIDZgAh"
    "AAABJAcGFRQXFjMgNzARBiEkJyY1NDc2NyYHBgcwESQzIAUwBPb+scPLZ1rtAS3OpP6u/kvInIxmxlSUh18BD8gBYAEiAkATnaPI"
    "eWpcmf7thgHGmt6zq31OAxQTKQEAPyYAAQB9/8kD2ANSABMAACU2NzYnJicwIRYXFgcGBQYnMBEWAYevGRtJPpsBcYIcgU9K/pLB"
    "k53eLlFXi3mapDPky70uGDcA/z0AAf+r/gwEEQImABMAACE2JzQnMCEWFRAHBgcGITARIDc2AmVJAjQBZjJYf9/m/jcBNZyYZ7WR"
    "eZZ0/veDvWJlAQBEQQABAH7+rgY9Au4AHwAAARYHBgcGIyInJBE0NzAhBhUUFxYzMjc2NzY1NCcwIRYGPAFlfeqxjMCZ/qMoAWYq"
    "yTdOOD3VOCFlAWZnATitstwtIixjAWuMsKCFskoUEDahX3ek3qT////s/gwCagJYECcAfADa/wYQBgB9AAAAAf/sAAACVQJYABEA"
    "AAEUBwYjMCEwETAzMjc2NTA1IQJVRECA/ptiRCwxAWYBc7ZhXAEALDFqkQAB/+wAAANYAlgAGwAAITAjIicGIzAjMBEwMzI3NjUw"
    "NSEVFBcWMzAzMANY+25NTW77YkQsMQFmMSxEYm1tAQAsMWqRkWoxLP///+z+rAJqAlgQJwB7ANr+rBAGAGYAAP//AKwAAAISBhQQ"
    "BgBgAAAAAQCsAAADFQYUABEAABMwESERFBcWMzAzMBEwISInJqwBZjEsRGL+m4BARAFzBKH7s2oxLP8AXGEA////7P6dAlUCWBAn"
    "AHoBV/6dEAYAfQAA////7AAAAmoD6BAnAHsA2gNSEAYAfQAA////7AAAA1gD6BAnAHsA2gNSEAYAfgAA//8Anf4MBcIEoRAmAGEA"
    "ABAHAHoCcQQL//8Aff/JA9gDUhAGAGIAAP///6v+DAQRAiYQBgBjAAAAAf+r/gwFDgImAB8AACUGBwYHBiEwESA3Njc2JzQnMCEW"
    "FxYXFjMwMzARMCMiA/QWJn/f5v43ATWcmk9JAjQBZgsJIjosSUuCVhpROb1iZQEARENtZbeReSIgfTss/wD///+r/gwEEQOnECYA"
    "YwAAEAcAegLVAxEAAf/s/+MIOALuAEEAAAUGIyInJicGBwYjIicGIzAhMBEwMzI3NicwJzAhMBUUFxYXFjc2NTAhFBcWMzI1MBEw"
    "ITARFBcWMzAzMBEwISInBgYEQ3FROpUKI4pIRv9TSlf+9GJELDIBAQFmLRtTRxglAWYTJEJ9AWYxLERi/vRQMVgRDB1IYYUkEmBO"
    "AQAsMmmRnCRiOwEBNlTVzTJfzgEm/tlqMSz/ADQ3AAAB/+wAAAJVBhQADQAAARQHBiMhETMyNzY1ESECVURAgP6bYkQsMQFmAXO2"
    "YVwBACwxagRNAAAC/+z/0AReAnwAEQAvAAAlNjU0JyYnJgcGBwYHBgcWMzIlNjc2MzIXFhcWFRQHBiMiJyYnBiMwIzARMDMyNzYC"
    "8yIXBiYLKB8RHgUEDjw7J/5DJGxNn55PuxcIYnjG7HwaB0BooXU+Ny7jFxwpFwYaCAICEyEeHBQotGBYPyRVpTUwjkVVQw4PMAEA"
    "Jh///wB+/q4GPQOnECYAZAAAEAcAegKjAxH////sAAACVQPZECYAZgAAEAcAegFXA0MAAgCFAAAE7gLuAAsAKQAAASYnJicGBwYV"
    "FDMyEyY1MCEWFxYXFjMwMzARMCMiJyYnBiciJyY1NDc2Ar8OCAQFXyktRGEBBQFmAiMUKUQLS+BcR0IRbOw4OsnYagE9KDMbFwog"
    "IzYwAaEhFciOUhos/wAiHyNBAQ8wur6KRAAAAv+r/gwFGAKWACUANQAAISInJicmNTQ3Njc2NzYXFhcWFzAzMBEwIwYHBgcGITAR"
    "Fjc2NzYTJicmBwYHBhUUFxYzMDM0AsogY99dYggckW2Z9F9ZNRQHuMkJP1/a9v3T76yuV2U9Bi8dJyodHiMkInoCBVFUhDQsoTgq"
    "AQE6N5o5Uf8AW2WXSlMBAAgbHDZAAZQpJxgBAR0eHC0TEycAAAEAAAAAAJYAlgADAAA1MxUjlpaWlgACAAAAAAGQAJYAAwAHAAA3"
    "MxUjJzMVI/qWlvqWlpaWlpYAAwAA/wYBkACWAAMABwALAAAXMxUjEzMVIyczFSN9lpZ9lpb6lpZklgGQlpaW////7AAAAlUCWBAG"
    "AGYAAP///+wAAANYAlgQBgBnAAAAAAAAAAcAWgADAAEECQAAATAAAAADAAEECQABABYBMAADAAEECQACAAgBRgADAAEECQADACAB"
    "TgADAAEECQAEACABTgADAAEECQAFABgBbgADAAEECQAGAB4BhgBDAG8AcAB5AHIAaQBnAGgAdAAgACgAYwApACAAMgAwADAAMwAg"
    "AGIAeQAgAEIAaQB0AHMAdAByAGUAYQBtACwAIABJAG4AYwAuACAAQQBsAGwAIABSAGkAZwBoAHQAcwAgAFIAZQBzAGUAcgB2AGUA"
    "ZAAuAAoAQwBvAHAAeQByAGkAZwBoAHQAIAAoAGMAKQAgADIAMAAwADYAIABiAHkAIABUAGEAdgBtAGoAbwBuAGcAIABCAGEAaAAu"
    "ACAAQQBsAGwAIABSAGkAZwBoAHQAcwAgAFIAZQBzAGUAcgB2AGUAZAAuAAoARABlAGoAYQBWAHUAIABjAGgAYQBuAGcAZQBzACAA"
    "YQByAGUAIABpAG4AIABwAHUAYgBsAGkAYwAgAGQAbwBtAGEAaQBuAAoARABlAGoAYQBWAHUAIABTAGEAbgBzAEIAbwBsAGQARABl"
    "AGoAYQBWAHUAIABTAGEAbgBzACAAQgBvAGwAZABWAGUAcgBzAGkAbwBuACAAMgAuADMANwBEAGUAagBhAFYAdQBTAGEAbgBzAC0A"
    "QgBvAGwAZAAAAAMAAAAAAAD/2ABaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAgAAv//AAMAAQAAAAwAAAAAAAAAAgADAAEAXwAB"
    "AGUAZQABAGgAeQABAAAAAQAAAAoAHAAeAAFERkxUAAgABAAAAAD//wAAAAAAAAABAAAACgCSAJQAFERGTFQAemFyYWIAhGFybW4A"
    "hGJyYWkAhGNhbnMAhGNoZXIAhGN5cmwAhGdlb3IAhGdyZWsAhGhhbmkAhGhlYnIAhGthbmEAhGxhbyAAhGxhdG4AhG1hdGgAhG5r"
    "byAAhG9nYW0AhHJ1bnIAhHRmbmcAhHRoYWkAhAAEAAAAAP//AAAAAAAAAAAAAAAA"
)


_FONTS = {}


def font(size):
    size = int(size)
    if size not in _FONTS:
        _FONTS[size] = ImageFont.truetype(io.BytesIO(base64.b64decode(FONT_B64)), size,
                                          layout_engine=ImageFont.Layout.BASIC)
    return _FONTS[size]


# ---------------------------------------------------------------- state
S = {"targets": {}, "pending": {}}
FLOW = {}   # تنظیمات نیمه‌کاره‌ی هر کاربر
WAIT = {}   # کاربر منتظر معرفی گروه/کانال


def load_state():
    global S
    if os.path.exists(STATE_FILE):
        try:
            with open(STATE_FILE, encoding="utf-8") as f:
                S = json.load(f)
        except Exception:
            pass
    S.setdefault("targets", {})
    S.setdefault("pending", {})
    S.setdefault("fake_price", None)   # قیمت دستی ادمین (None = واقعی)
    S.setdefault("fake_last", None)    # قیمت قبلی فیک برای فلش بالا/پایین
    S.setdefault("api_url", "")        # URL تنها API قیمت؛ فقط از پنل ادمین تنظیم می‌شود


def save():
    try:
        with open(STATE_FILE, "w", encoding="utf-8") as f:
            json.dump(S, f, ensure_ascii=False)
    except Exception as e:
        print("save error:", e)


# ---------------------------------------------------------------- telegram helpers
def api(method, _timeout=40, **params):
    try:
        r = requests.post(API + method, json=params, timeout=_timeout, proxies=PROXIES)
        return r.json()
    except Exception as e:
        return {"ok": False, "error_code": 0, "description": f"network: {e}"}


def send_text(chat_id, text, kb=None):
    p = {"chat_id": chat_id, "text": text, "disable_web_page_preview": True}
    if kb:
        p["reply_markup"] = kb
    return api("sendMessage", **p)


def show(chat_id, mid, text, kb=None):
    """پیام قبلی رو ویرایش می‌کنه (اگه نشد، پیام جدید می‌فرسته)."""
    if mid:
        p = {"chat_id": chat_id, "message_id": mid, "text": text, "disable_web_page_preview": True}
        if kb:
            p["reply_markup"] = kb
        r = api("editMessageText", **p)
        if r.get("ok") or "not modified" in (r.get("description") or ""):
            return r
    return send_text(chat_id, text, kb)


def fd(x):
    return str(x).translate(str.maketrans("0123456789", "۰۱۲۳۴۵۶۷۸۹"))


def btn(text, data=None, url=None):
    b = {"text": text}
    if url:
        b["url"] = url
    else:
        b["callback_data"] = data
    return b


# ---------------------------------------------------------------- price
# فقط یک منبع قیمت: API که ادمین از پنل وارد می‌کند.
# هیچ کانال مرجع، OCR، TGJU، صرافی یا API دیگری برای قیمت استفاده نمی‌شود.

_API_CACHE = {"ts": 0, "price": None, "sell": None, "buy": None, "updated_at": None, "via": None}


def _api_url():
    return str(S.get("api_url") or "").strip()


def _api_number(v):
    try:
        if isinstance(v, bool) or v is None:
            return None
        if isinstance(v, (int, float)):
            return float(v)
        return float(str(v).replace(",", "").replace("٬", "").replace("،", "").replace(" ", "").strip())
    except Exception:
        return None


def _to_toman(v):
    v = _api_number(v)
    if v is None or v <= 0:
        return None
    # اگر API ریال بدهد، به تومان تبدیل می‌کنیم.
    return v / 10 if v > 1_000_000 else v


SCRAPE_URL = "https://alanchand.com/"


def _digits_en(x):
    """ارقام فارسی/عربی و جداکننده‌ها را به عدد انگلیسی تبدیل می‌کند."""
    tr = str.maketrans("۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩", "01234567890123456789")
    return str(x).translate(tr)


class _DollarParser(HTMLParser):
    """بدون نیاز به bs4: tr مربوط به دلار → المنت با کلاس sellPrice."""

    def __init__(self, exact=True):
        super().__init__()
        self.exact = exact
        self.in_row = False
        self.row_depth = 0
        self.cap = False
        self.cap_depth = 0
        self.text = []
        self.done = False

    def _title_ok(self, title):
        title = (title or "").strip()
        if self.exact:
            return title == "قیمت دلار آمریکا"
        return "دلار" in title and "قیمت" in title and "تتر" not in title

    def handle_starttag(self, tag, attrs):
        if self.done:
            return
        a = dict(attrs)
        if not self.in_row:
            if tag == "tr" and self._title_ok(a.get("title")):
                self.in_row = True
                self.row_depth = 1
            return
        if tag == "tr":
            self.row_depth += 1
        if self.cap:
            self.cap_depth += 1
        elif "sellprice" in (a.get("class") or "").lower():
            self.cap = True
            self.cap_depth = 1

    def handle_endtag(self, tag):
        if self.done or not self.in_row:
            return
        if self.cap:
            self.cap_depth -= 1
            if self.cap_depth <= 0:
                self.cap = False
                if "".join(self.text).strip():
                    self.done = True
                    return
        if tag == "tr":
            self.row_depth -= 1
            if self.row_depth <= 0:
                self.in_row = False

    def handle_data(self, data):
        if self.cap and not self.done:
            self.text.append(data)


def _extract_dollar(html):
    """چند روش پشت‌سرهم برای پیدا کردن قیمت فروش دلار در HTML."""
    for exact in (True, False):
        ps = _DollarParser(exact)
        try:
            ps.feed(html)
        except Exception:
            pass
        txt = "".join(ps.text).strip()
        if re.search(r"\d", _digits_en(txt)):
            return txt
    # روش ۳: نزدیک عبارت «دلار آمریکا» اولین المنت sellPrice
    m = re.search(r"دلار آمریکا.{0,1500}?sellPrice[^>]*>(?:\s*<[^>]+>)*\s*([0-9۰-۹٠-٩,٬،.]{4,})",
                  html, re.S | re.I)
    if m:
        return m.group(1).strip()
    # روش ۴: متن خالص صفحه ؛ «دلار آمریکا» و بعدش اولین عدد بزرگ
    plain = re.sub(r"<(script|style)[^>]*>.*?</\1>", " ", html, flags=re.S | re.I)
    plain = re.sub(r"<[^>]+>", " ", plain)
    plain = unescape(plain)
    m = re.search(r"دلار آمریکا\D{0,40}?([0-9۰-۹٠-٩][0-9۰-۹٠-٩,٬،.]{4,})", plain)
    if m:
        return m.group(1).strip()
    return None


def scrape(url=SCRAPE_URL):
    """قیمت فروش دلار را از سایت alanchand.com اسکرپ می‌کند (متن خام) — بدون وابستگی به bs4."""
    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
                      "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "fa-IR,fa;q=0.9,en;q=0.8",
    }
    resp = requests.get(url, headers=headers, timeout=20, proxies=PROXIES)
    if resp.status_code != 200:
        raise RuntimeError("سایت خطای HTTP %s داد (احتمالاً IP سرور بلاک شده)." % resp.status_code)
    resp.encoding = "utf-8"
    html = resp.text
    txt = _extract_dollar(html)
    if txt:
        return txt
    # تشخیص علت
    low = html.lower()
    tm = re.search(r"<title[^>]*>(.*?)</title>", html, re.S | re.I)
    title = re.sub(r"\s+", " ", tm.group(1)).strip()[:60] if tm else "—"
    why = ""
    if any(x in low for x in ("cloudflare", "just a moment", "captcha", "challenge", "access denied")):
        why = " | به‌نظر صفحه‌ی ضد‌ربات/بلاک است"
    raise RuntimeError("قیمت دلار در صفحه پیدا نشد | طول صفحه: %d | عنوان: %s%s"
                       % (len(html), title, why))


def _fetch_scrape():
    raw = scrape()
    clean = re.sub(r"[^0-9.]", "", _digits_en(raw))
    sell = _to_toman(clean)
    if sell is None:
        raise RuntimeError("قیمت اسکرپ‌شده نامعتبر است: %r" % raw)
    return {"sell": sell, "buy": None, "updated_at": now_text(), "via": "وب‌اسکرپینگ alanchand"}


def _fetch_api(url):
    try:
        r = requests.get(
            url,
            timeout=15,
            headers={
                "Accept": "application/json",
                "User-Agent": "Mozilla/5.0 (compatible; DollarStickerBot/1.0)",
            },
            proxies=PROXIES,
        )
    except Exception as e:
        raise RuntimeError("اتصال به API نشد: %s" % e)

    if r.status_code in (401, 403):
        raise RuntimeError("API رد شد؛ توکن یا URL را بررسی کن.")
    if r.status_code != 200:
        raise RuntimeError("API خطای HTTP %s داد." % r.status_code)

    try:
        data = r.json()
    except Exception:
        raise RuntimeError("پاسخ API JSON نیست.")

    # ساختار فعلی الان‌چند:
    # {"usd":{"sell":269300,"buy":266600,"updated_at":"..."}}
    usd = data.get("usd") if isinstance(data, dict) else None
    if not isinstance(usd, dict):
        raise RuntimeError("بخش usd در پاسخ API پیدا نشد.")

    sell = _to_toman(usd.get("sell"))
    buy = _to_toman(usd.get("buy"))
    if sell is None:
        raise RuntimeError("فیلد usd.sell در پاسخ API پیدا نشد یا نامعتبر است.")
    return {"sell": sell, "buy": buy, "updated_at": usd.get("updated_at"), "via": "API ادمین"}


def api_price_snapshot(force=False):
    """قیمت دلار: اول API ادمین (اگر تنظیم شده)، در صورت نبود/خطا وب‌اسکرپینگ alanchand."""
    now = time.time()
    if not force and _API_CACHE["price"] and now - _API_CACHE["ts"] < 15:
        return {
            "sell": _API_CACHE["sell"],
            "buy": _API_CACHE["buy"],
            "price": _API_CACHE["price"],
            "updated_at": _API_CACHE["updated_at"],
            "via": _API_CACHE.get("via") or "API ادمین",
        }

    url = _api_url()
    data, errs = None, []
    if url:
        try:
            data = _fetch_api(url)
        except Exception as e:
            errs.append("API: %s" % e)
    if data is None:
        try:
            data = _fetch_scrape()
        except Exception as e:
            errs.append("اسکرپ: %s" % e)
            raise RuntimeError(" | ".join(errs))

    _API_CACHE.update(ts=now, price=data["sell"], sell=data["sell"], buy=data["buy"],
                      updated_at=data["updated_at"], via=data["via"])
    return {"sell": data["sell"], "buy": data["buy"], "price": data["sell"],
            "updated_at": data["updated_at"], "via": data["via"]}


def price_report():
    """گزارش فقط از API واردشده توسط ادمین."""
    rep = {"price": None, "closed": False, "source": None, "api": None, "api_err": None}
    try:
        data = api_price_snapshot()
        rep["api"] = data
        rep["price"] = int(round(data["sell"]))
        rep["source"] = data.get("via") or "API ادمین"
    except Exception as e:
        rep["api_err"] = str(e)[:500]
    return rep


def get_price():
    """(قیمت, بازار_بسته؟)"""
    if S.get("fake_price") is not None:
        return float(S["fake_price"]), True

    rep = price_report()
    if not rep["price"]:
        raise RuntimeError(rep["api_err"] or "قیمت از API دریافت نشد.")

    S["last_known_price"] = rep["price"]
    S["last_known_ts"] = time.time()
    print("💲 %s (%s)" % (format(rep["price"], ","), rep.get("source")))
    return int(rep["price"]), False


def _fmt_n(v):
    return "—" if v is None else format(float(v), ",.0f")


def format_report(rep):
    if not rep.get("price"):
        return "❌ قیمت دریافت نشد.\n\n" + (rep.get("api_err") or "API تنظیم نشده است.")

    data = rep.get("api") or {}
    return (
        "💲 قیمت دلار: %s تومان\n"
        "📌 نوع قیمت: فروش\n"
        "🟢 فروش: %s تومان\n"
        "🔵 خرید: %s تومان\n"
        "🕐 آخرین بروزرسانی: %s\n"
        "🔗 منبع: %s"
        % (format(rep["price"], ","), _fmt_n(data.get("sell")),
           _fmt_n(data.get("buy")), data.get("updated_at") or "—", rep.get("source") or "—")
    )


def cached_price():
    """کش کوتاه برای جلوگیری از درخواست‌های پشت‌سرهم به API."""
    global _PC
    if "_PC" not in globals() or not isinstance(_PC, dict):
        _PC = {"ts": 0, "price": None}

    if S.get("fake_price") is not None:
        return float(S["fake_price"]), True

    now = time.time()
    if _PC.get("price") and (now - _PC.get("ts", 0)) < 10:
        return _PC["price"]

    p = get_price()
    _PC["ts"] = now
    _PC["price"] = p
    try:
        record_price(p[0])
    except Exception:
        pass
    return p


def record_price(p):
    """تاریخچه‌ی کوتاه قیمت برای نمودار روی استیکر."""
    try:
        h = S.setdefault("hist", [])
        now = time.time()
        if not h or round(float(h[-1][1]), 2) != round(float(p), 2) or now - h[-1][0] >= 300:
            h.append([now, round(float(p), 2)])
            del h[:-60]
    except Exception:
        pass


# ---------------------------------------------------------------- date
def tehran_now():
    return datetime.now(timezone.utc) + timedelta(hours=3, minutes=30)


def g2j(gy, gm, gd):
    g_d_m = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334]
    if gy > 1600:
        jy = 979
        gy -= 1600
    else:
        jy = 0
        gy -= 621
    gy2 = gy + 1 if gm > 2 else gy
    days = (365 * gy + (gy2 + 3) // 4 - (gy2 + 99) // 100 + (gy2 + 399) // 400
            - 80 + gd + g_d_m[gm - 1])
    jy += 33 * (days // 12053)
    days %= 12053
    jy += 4 * (days // 1461)
    days %= 1461
    if days > 365:
        jy += (days - 1) // 365
        days = (days - 1) % 365
    if days < 186:
        jm, jd = 1 + days // 31, 1 + days % 31
    else:
        jm, jd = 7 + (days - 186) // 30, 1 + (days - 186) % 30
    return jy, jm, jd


def now_text():
    n = tehran_now()
    jy, jm, jd = g2j(n.year, n.month, n.day)
    return f"{jy % 100:02d}/{jm:02d}/{jd:02d}  {n:%H:%M:%S}"


# ---------------------------------------------------------------- sticker (flat style)
# کلمات فارسی از قبل به شکل «متصل و راست‌به‌چپ» آماده شدن
WORDS = {
    "نرخ دلار": "\ufead\ufe8e\ufedf\ufea9 \ufea5\ufeae\ufee7",
    "تومان": "\ufee5\ufe8e\ufee3\ufeee\ufe97",
    "بر پایه تتر (بازار بسته)": "(\ufeea\ufe98\ufeb4\ufe91 \ufead\ufe8d\ufeaf\ufe8e\ufe91) \ufeae\ufe98\ufe97 \ufeea\ufbfe\ufe8e\ufb58 \ufeae\ufe91",
}

THEMES = {
    # زمینه‌ی شیشه‌ای بی‌رنگ ، فقط نوشته‌ها رنگی: سبز = بالا ، قرمز = پایین ، سفید = ثابت
    "up": dict(col=(74, 255, 152), glow=(30, 255, 120), sub=(176, 255, 210)),
    "down": dict(col=(255, 86, 114), glow=(255, 40, 84), sub=(255, 178, 194)),
    "flat": dict(col=(255, 255, 255), glow=(214, 228, 255), sub=(236, 241, 250)),
}


def _r2(x):
    return round(float(x), 2)


def split_price(p):
    p = _r2(p)
    ip = int(p)
    fr = int(round((p - ip) * 100))
    if fr >= 100:
        ip, fr = ip + 1, 0
    return ip, fr


def fmt_price(p):
    """قیمت دقیق: اگه اعشار داشت تا دو رقم نشون میده"""
    ip, fr = split_price(p)
    return f"{ip:,}" + (f".{fr:02d}" if fr else "")


def fmt_delta(dv):
    if dv == 0:
        return "0"
    if abs(dv - round(dv)) < 1e-9:
        return f"{dv:+,.0f}"
    return f"{dv:+,.2f}"


def _spline(pts, n=10):
    """منحنی نرم از بین نقطه‌ها (Catmull-Rom)"""
    if len(pts) < 3:
        return pts
    P = [pts[0]] + list(pts) + [pts[-1]]
    out = []
    for i in range(1, len(P) - 2):
        p0, p1, p2, p3 = P[i - 1], P[i], P[i + 1], P[i + 2]
        for s in range(n):
            t = s / n
            t2, t3 = t * t, t * t * t
            out.append(tuple(0.5 * ((2 * p1[j]) + (-p0[j] + p2[j]) * t + (2 * p0[j] - 5 * p1[j] + 4 * p2[j] - p3[j]) * t2
                                    + (-p0[j] + 3 * p1[j] - 3 * p2[j] + p3[j]) * t3) for j in range(2)))
    out.append(pts[-1])
    return out


def make_sticker(price, last, closed=False):
    """استیکر شیشه‌ای با آیکون‌های خطی مثل نمونه‌های کانال (لامپ، ابر، ربات، ستاره، خط‌چین)."""
    price = _r2(price)
    if last is None or price == _r2(last):
        key, dv = "flat", 0.0
    elif price > _r2(last):
        key, dv = "up", _r2(price - _r2(last))
    else:
        key, dv = "down", _r2(price - _r2(last))
    th = THEMES[key]
    col, glow, sub = th["col"], th["glow"], th["sub"]

    K = 3
    W, H = 512, 512   # مربع‌تر مثل نمونه‌ها
    size = (W * K, H * K)

    def k(v):
        return int(round(v * K))

    def fk(sz):
        return font(sz * K)

    def new():
        return Image.new("RGBA", size, (0, 0, 0, 0))

    def blur(layer, r):
        return layer.filter(ImageFilter.GaussianBlur(k(r)))

    box = (k(18), k(18), k(W - 18), k(H - 18))
    R = k(56)
    mask = Image.new("L", size, 0)
    ImageDraw.Draw(mask).rounded_rectangle(box, R, fill=255)
    img = new()

    # —— بدنه شیشه نیمه‌شفاف تیره (پس‌زمینه چت از پشت معلوم می‌شود) ——
    gm = Image.linear_gradient("L").resize(size)
    tint = Image.new("RGBA", size, (18, 14, 10, 0))
    tint.putalpha(ImageChops.multiply(gm.point(lambda v: 100 + v * 50 // 255), mask))
    img.alpha_composite(tint)

    # لبه ساده و مات (بدون براق)
    ed = new()
    e = ImageDraw.Draw(ed)
    e.rounded_rectangle(box, R, outline=(255, 255, 255, 55), width=k(2))
    img.alpha_composite(ed)

    # —— لایه آیکون‌های تزئینی (لامپ، ابر، ربات، ستاره، خط‌چین) ——
    ico = new()
    idr = ImageDraw.Draw(ico)
    ic = sub + (130,)          # رنگ کم‌رنگ آیکون‌ها
    ic2 = sub + (80,)         # کم‌رنگ‌تر برای خط‌چین

    def sparkle(cx, cy, s=10):
        s = k(s)
        idr.line([(cx, cy - s), (cx, cy + s)], fill=ic, width=k(2))
        idr.line([(cx - s, cy), (cx + s, cy)], fill=ic, width=k(2))
        idr.line([(cx - s * 0.7, cy - s * 0.7), (cx + s * 0.7, cy + s * 0.7)], fill=ic, width=k(1))
        idr.line([(cx - s * 0.7, cy + s * 0.7), (cx + s * 0.7, cy - s * 0.7)], fill=ic, width=k(1))

    def lightbulb(cx, cy, s=22):
        # حباب
        idr.ellipse([cx - k(s * 0.55), cy - k(s * 0.9), cx + k(s * 0.55), cy + k(s * 0.2)],
                    outline=ic, width=k(2))
        # پایه
        idr.arc([cx - k(s * 0.3), cy + k(s * 0.05), cx + k(s * 0.3), cy + k(s * 0.45)],
                0, 180, fill=ic, width=k(2))
        idr.line([(cx - k(s * 0.22), cy + k(s * 0.5)), (cx + k(s * 0.22), cy + k(s * 0.5))],
                 fill=ic, width=k(2))
        idr.line([(cx - k(s * 0.18), cy + k(s * 0.62)), (cx + k(s * 0.18), cy + k(s * 0.62))],
                 fill=ic, width=k(2))
        # رشته داخل
        idr.arc([cx - k(s * 0.28), cy - k(s * 0.55), cx + k(s * 0.28), cy - k(s * 0.05)],
                200, 340, fill=ic, width=k(1))

    def cloud_dl(cx, cy, s=20):
        # ابر ساده خطی
        idr.arc([cx - k(s * 0.85), cy - k(s * 0.35), cx - k(s * 0.05), cy + k(s * 0.45)],
                30, 330, fill=ic, width=k(2))
        idr.arc([cx - k(s * 0.25), cy - k(s * 0.7), cx + k(s * 0.55), cy + k(s * 0.15)],
                200, 90, fill=ic, width=k(2))
        idr.arc([cx + k(s * 0.05), cy - k(s * 0.25), cx + k(s * 0.85), cy + k(s * 0.5)],
                250, 120, fill=ic, width=k(2))
        idr.line([(cx - k(s * 0.55), cy + k(s * 0.4)), (cx + k(s * 0.55), cy + k(s * 0.4))],
                 fill=ic, width=k(2))
        # فلش دانلود زیر ابر
        idr.line([(cx, cy + k(s * 0.5)), (cx, cy + k(s * 1.15))], fill=ic, width=k(2))
        idr.line([(cx - k(s * 0.28), cy + k(s * 0.85)), (cx, cy + k(s * 1.2)),
                  (cx + k(s * 0.28), cy + k(s * 0.85))], fill=ic, width=k(2))

    def bot_face(cx, cy, s=18):
        # سر ربات/چت
        idr.rounded_rectangle([cx - k(s * 0.7), cy - k(s * 0.55), cx + k(s * 0.7), cy + k(s * 0.55)],
                              k(6), outline=ic, width=k(2))
        # آنتن
        idr.line([(cx, cy - k(s * 0.55)), (cx, cy - k(s * 0.95))], fill=ic, width=k(2))
        idr.ellipse([cx - k(4), cy - k(s * 1.1), cx + k(4), cy - k(s * 0.85)], outline=ic, width=k(2))
        # چشم‌ها
        idr.ellipse([cx - k(s * 0.35), cy - k(s * 0.2), cx - k(s * 0.1), cy + k(s * 0.05)], fill=ic)
        idr.ellipse([cx + k(s * 0.1), cy - k(s * 0.2), cx + k(s * 0.35), cy + k(s * 0.05)], fill=ic)
        # دهان
        idr.arc([cx - k(s * 0.25), cy + k(s * 0.05), cx + k(s * 0.25), cy + k(s * 0.4)],
                20, 160, fill=ic, width=k(2))

    def doc_lines(cx, cy, s=16):
        idr.rounded_rectangle([cx - k(s * 0.6), cy - k(s * 0.75), cx + k(s * 0.6), cy + k(s * 0.75)],
                              k(4), outline=ic, width=k(2))
        for i, yoff in enumerate((-0.35, -0.05, 0.25)):
            idr.line([(cx - k(s * 0.35), cy + k(s * yoff)), (cx + k(s * 0.35), cy + k(s * yoff))],
                     fill=ic, width=k(2))

    def dashed_curve(pts, w=2):
        """خط‌چین نرم بین نقاط"""
        if len(pts) < 2:
            return
        smooth = _spline([(k(x), k(y)) for x, y in pts], n=8) if len(pts) >= 3 else [(k(x), k(y)) for x, y in pts]
        step = max(2, len(smooth) // 12)
        for i in range(0, len(smooth) - 1, step * 2):
            a = smooth[i]
            b = smooth[min(i + step, len(smooth) - 1)]
            idr.line([a, b], fill=ic2, width=k(w))

    # چیدمان آیکون‌ها (مختصات منطقی کارت ۵۱۲×۵۱۲)
    lightbulb(k(70), k(70), 20)
    sparkle(k(115), k(48), 8)
    sparkle(k(400), k(80), 7)
    bot_face(k(440), k(75), 16)
    cloud_dl(k(75), k(420), 18)
    doc_lines(k(440), k(420), 15)
    sparkle(k(250), k(470), 6)
    # خط‌چین‌های تزئینی
    dashed_curve([(55, 110), (90, 180), (60, 260), (100, 340), (70, 390)], w=2)
    dashed_curve([(450, 110), (420, 200), (455, 300), (420, 380)], w=2)
    dashed_curve([(130, 450), (220, 470), (320, 455), (400, 440)], w=1)

    img.alpha_composite(ico)

    cx = W // 2

    def neon(xy, text, f, color, glow_c, anchor="mm", strength=1.0):
        nonlocal img
        sh = new()
        ImageDraw.Draw(sh).text((xy[0], xy[1] + k(3)), text, font=f, fill=(0, 0, 0, 170), anchor=anchor)
        img.alpha_composite(blur(sh, 3))
        gl = new()
        ImageDraw.Draw(gl).text(xy, text, font=f, fill=glow_c + (int(230 * strength),), anchor=anchor)
        img.alpha_composite(blur(gl, 8))
        ImageDraw.Draw(img).text(xy, text, font=f, fill=color + (255,), anchor=anchor)

    d = ImageDraw.Draw(img)

    # عنوان
    neon((k(cx), k(95)), fa("نرخ دلار"), fk(40), sub, glow, strength=0.55)

    # قیمت + فلش
    ip, fr = split_price(price)
    main = f"{ip:,}"
    frac = f".{fr:02d}" if fr else ""
    aw, gap = 42, 16
    psize = 100
    while psize > 44:
        pw = d.textlength(main, font=fk(psize)) / K + (d.textlength(frac, font=fk(int(psize * 0.5))) / K + 4 if frac else 0)
        if pw + gap + aw <= 420:
            break
        psize -= 4
    pf, ff = fk(psize), fk(int(psize * 0.5))
    mw = d.textlength(main, font=pf) / K
    fw = d.textlength(frac, font=ff) / K + 4 if frac else 0
    total = mw + fw + gap + aw
    x0 = cx - total / 2
    base = 200
    neon((k(x0), k(base)), main, pf, col, glow, "ls")
    if frac:
        neon((k(x0 + mw + 4), k(base)), frac, ff, sub, glow, "ls", strength=0.7)
    ax = x0 + mw + fw + gap + aw / 2
    ay = base - psize * 0.32
    shape = new()
    sd = ImageDraw.Draw(shape)
    gsh = new()
    if key == "up":
        poly = [(k(ax), k(ay - 18)), (k(ax - 20), k(ay + 16)), (k(ax + 20), k(ay + 16))]
        sd.polygon(poly, fill=col + (255,))
        ImageDraw.Draw(gsh).polygon(poly, fill=glow + (230,))
    elif key == "down":
        poly = [(k(ax), k(ay + 18)), (k(ax - 20), k(ay - 16)), (k(ax + 20), k(ay - 16))]
        sd.polygon(poly, fill=col + (255,))
        ImageDraw.Draw(gsh).polygon(poly, fill=glow + (230,))
    else:
        bar = (k(ax - 18), k(ay - 4), k(ax + 18), k(ay + 4))
        sd.rounded_rectangle(bar, k(4), fill=col + (255,))
        ImageDraw.Draw(gsh).rounded_rectangle(bar, k(4), fill=glow + (230,))
    img.alpha_composite(blur(gsh, 7))
    img.alpha_composite(shape)

    # تومان (بدون عدد تغییر — مثل نمونه)
    neon((k(cx), k(275)), fa("تومان"), fk(36), sub, glow, strength=0.5)

    # زمان + برچسب
    if closed:
        neon((k(cx), k(340)), now_text(), fk(26), sub, glow, strength=0.4)
        neon((k(cx), k(380)), fa("بر پایه تتر (بازار بسته)"), fk(22), sub, glow, strength=0.4)
    else:
        neon((k(cx), k(355)), now_text(), fk(27), sub, glow, strength=0.4)

    img = img.resize((W, H), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="WEBP", lossless=True, method=6)
    if buf.tell() > 500 * 1024:
        buf = io.BytesIO()
        img.save(buf, format="WEBP", quality=95, alpha_quality=100, method=6)
    buf.seek(0)
    return buf



def fa(t):
    return WORDS.get(t, t)


def send_sticker(chat_id, price, last, closed=False):
    try:
        r = requests.post(
            API + "sendSticker",
            data={"chat_id": chat_id},
            files={"sticker": ("s.webp", make_sticker(price, last, closed), "image/webp")},
            timeout=40,
            proxies=PROXIES,
        )
        return r.json()
    except Exception as e:
        return {"ok": False, "error_code": 0, "description": f"network: {e}"}


# ---------------------------------------------------------------- targets
KIND_ICON = {"user": "👤", "group": "👥", "channel": "📢"}


def ensure_target(chat_id, owner, title, kind):
    key = str(chat_id)
    t = S["targets"].get(key)
    if not t:
        t = {"chat_id": chat_id, "owner": owner, "title": title, "kind": kind, "ready": False,
             "start": 0, "end": 0, "all24": True, "interval": 15, "last_sent": 0,
             "last_price": None, "warned": False}
        S["targets"][key] = t
    else:
        t["title"] = title
        t["owner"] = owner
    save()
    return t


def interval_text(m):
    if m < 60:
        return f"{fd(m)} دقیقه"
    return f"{fd(m // 60)} ساعت"


def window_text(t):
    if t.get("all24") or t["start"] == t["end"]:
        return "۲۴ ساعته (کل شبانه‌روز)"
    a = fd("%02d" % t["start"])
    b = fd("%02d" % t["end"])
    return "از %s:۰۰ تا %s:۰۰" % (a, b)


def window_ok(t):
    if t.get("all24") or t["start"] == t["end"]:
        return True
    n = tehran_now()
    m = n.hour * 60 + n.minute
    s, e = t["start"] * 60, t["end"] * 60
    return (s <= m <= e) if s < e else (m >= s or m <= e)


def summary_text(t):
    return (f"✅ تنظیمات ذخیره شد\n\n"
            f"📍 مقصد: {KIND_ICON.get(t['kind'], '')} {t['title']}\n"
            f"⏰ زمان: {window_text(t)}\n"
            f"🔁 فاصله‌ی ارسال: هر {interval_text(t['interval'])}")


def kb_detail(t):
    cid = t["chat_id"]
    return {"inline_keyboard": [
        [btn("⏰ تغییر زمان", f"edit:{cid}"), btn("🗑 حذف", f"del:{cid}")],
        [btn("🏠 منو", "home")],
    ]}


def kb_menu(uid):
    rows = [
        [btn("👤 برای خودم", "dest:me")],
        [btn("👥️ برای گروه‌های من", "dest:group")],
        [btn("📢 برای کانال‌های من", "dest:channel")],
    ]
    if any(t["owner"] == uid and t.get("ready") for t in S["targets"].values()):
        rows.append([btn("📋 مقصدهای من", "list")])
    if uid == ADMIN_ID:
        rows.append([btn("🛠 پنل مدیریت", "admin")])
    return {"inline_keyboard": rows}


def kb_admin():
    fp = S.get("fake_price")
    api_set = bool(S.get("api_url"))
    status = f"فیک: {fmt_price(fp)}" if fp is not None else ("واقعی (API)" if api_set else "واقعی (اسکرپ)")
    return {"inline_keyboard": [
        [btn(f"📊 وضعیت: {status}", "admin:status")],
        [btn("🔑 API", "admin:api")],
        [btn("✏️ قیمت دستی", "admin:set"), btn("🔄 واقعی کن", "admin:clear")],
        [btn("➕۱۰۰", "admin:+100"), btn("➕۵۰", "admin:+50"), btn("➕۱۰", "admin:+10")],
        [btn("➖۱۰", "admin:-10"), btn("➖۵۰", "admin:-50"), btn("➖۱۰۰", "admin:-100")],
        [btn("📤 تست استیکر (پیوی)", "admin:test")],
        [btn("🏠 منو", "home")],
    ]}


def show_admin(uid, mid=None):
    fp = S.get("fake_price")
    api_url = S.get("api_url") or "تنظیم نشده"
    masked = api_url
    if len(masked) > 70:
        masked = masked[:55] + "..." + masked[-10:]
    if fp is not None:
        body = (
            "🛠 پنل مدیریت\n\n"
            f"قیمت فعلی فیک: {fmt_price(fp)} تومان\n"
            f"🔑 API: {masked}\n\n"
            "با دکمه‌های ➕/➖ تغییر بده یا قیمت دستی بفرست.\n"
            "«تست استیکر» یک استیکر با همین قیمت به پیویت می‌فرستد."
        )
    else:
        api_status = (
            "قیمت واقعی از همین API گرفته می‌شود (در صورت خطا: اسکرپ alanchand)."
            if api_url != "تنظیم نشده"
            else "ℹ️ API وارد نشده؛ قیمت از وب‌اسکرپینگ alanchand.com گرفته می‌شود."
        )
        body = (
            "🛠 پنل مدیریت\n\n"
            f"🔑 API: {masked}\n"
            f"{api_status}\n\n"
            "برای تنظیم یا تغییر API روی دکمه 🔑 API بزن."
        )
    show(uid, mid, body, kb_admin())


MENU_TEXT = "✅ لطفاً مشخص کنید قیمت‌ها برای کجا ارسال شود:"


def show_menu(uid, mid=None):
    FLOW.pop(uid, None)
    WAIT.pop(uid, None)
    show(uid, mid, MENU_TEXT, kb_menu(uid))


def show_list(uid, mid=None):
    mine = [t for t in S["targets"].values() if t["owner"] == uid and t.get("ready")]
    if not mine:
        show(uid, mid, "هنوز مقصدی تنظیم نکردی.", kb_menu(uid))
        return
    rows = [[btn(f"{KIND_ICON.get(t['kind'], '')} {t['title']}", f"cfg:{t['chat_id']}")] for t in mine]
    rows.append([btn("🏠 منو", "home")])
    show(uid, mid, "📋 مقصدهای تو (برای تغییر یا حذف انتخاب کن):", {"inline_keyboard": rows})


# ---------------------------------------------------------------- setup steps
def hours_grid(prefix):
    rows, row = [], []
    for h in range(24):
        row.append(btn(f"{fd(f'{h:02d}')}:۰۰", f"{prefix}:{h}"))
        if len(row) == 4:
            rows.append(row)
            row = []
    return rows


def step_start(uid, chat_id, mid=None):
    t = S["targets"].get(str(chat_id), {})
    rows = hours_grid("sh")
    rows.append([btn("🕐 ۲۴ ساعته (کل شبانه‌روز)", "all24")])
    rows.append([btn("🏠 منو", "home")])
    return show(uid, mid,
                f"⏰ تنظیم زمان برای «{t.get('title', '')}»\n\n"
                "ارسال از چه ساعتی شروع بشه؟ (به وقت تهران)",
                {"inline_keyboard": rows})


def step_end(uid, mid, start):
    rows = hours_grid("eh")
    rows.append([btn("🏠 منو", "home")])
    return show(uid, mid,
                f"✅ شروع: {fd(f'{start:02d}')}:۰۰\n\nتا چه ساعتی ارسال بشه؟",
                {"inline_keyboard": rows})


def step_interval(uid, mid):
    opts = [15, 30, 60, 120, 180, 360, 720, 1440]
    rows, row = [], []
    for m in opts:
        row.append(btn(f"هر {interval_text(m)}", f"iv:{m}"))
        if len(row) == 2:
            rows.append(row)
            row = []
    rows.append([btn("🏠 منو", "home")])
    return show(uid, mid, "🔁 هر چند وقت یک‌بار قیمت ارسال بشه؟\n(از هر ۱۵ دقیقه تا هر ۲۴ ساعت)",
                {"inline_keyboard": rows})


def finish(uid, mid, interval):
    f = FLOW.get(uid)
    if not f:
        show(uid, mid, "جلسه‌ی تنظیم تموم شده. دوباره /start بزن.")
        return
    t = S["targets"].get(str(f["chat_id"]))
    if not t:
        show(uid, mid, "مقصد پیدا نشد. دوباره /start بزن.")
        return
    t.update(start=f.get("start", 0), end=f.get("end", 0), all24=f.get("all24", False),
             interval=interval, ready=True, last_sent=0, warned=False)
    save()
    FLOW.pop(uid, None)
    show(uid, mid, summary_text(t) + "\n\nاولین استیکر همین الان ارسال میشه 👇", kb_detail(t))
    try:
        p, c = cached_price()
        deliver(t, p, c)
    except Exception as e:
        send_text(uid, f"❌ قیمت دلار الان دریافت نشد: {e}")


# ---------------------------------------------------------------- permissions / registration
def check_post_rights(chat_id, kind):
    me = api("getChatMember", chat_id=chat_id, user_id=BOT_ID)
    if not me.get("ok"):
        return False, "ربات داخل این چت نیست. اول ربات رو اضافه کن."
    m = me["result"]
    st = m.get("status")
    if st in ("left", "kicked"):
        return False, "ربات داخل این چت نیست. اول ربات رو اضافه کن."
    if kind == "channel":
        if st != "administrator":
            return False, "ربات باید «ادمین» کانال باشه."
        if not m.get("can_post_messages"):
            return False, "توی تنظیمات ادمین ربات، گزینه‌ی «ارسال پیام» (Post Messages) رو فعال کن."
        return True, ""
    if st == "administrator":
        return True, ""
    msg = "اجازه‌ی ارسال پیام و استیکر برای ربات بسته است. ربات رو ادمین کن یا این اجازه رو بده."
    if st == "restricted":
        if not m.get("can_send_messages", True) or not m.get("can_send_other_messages", True):
            return False, msg
        return True, ""
    perms = api("getChat", chat_id=chat_id).get("result", {}).get("permissions")
    if perms and (not perms.get("can_send_messages", True) or not perms.get("can_send_other_messages", True)):
        return False, msg
    return True, ""


def owner_for(chat_id):
    o = S["pending"].get(str(chat_id))
    if o:
        return o
    r = api("getChatAdministrators", chat_id=chat_id)
    for a in r.get("result", []) or []:
        if a.get("status") == "creator" and not a["user"].get("is_bot"):
            return a["user"]["id"]
    for a in r.get("result", []) or []:
        if not a["user"].get("is_bot"):
            return a["user"]["id"]
    return None


def register_chat(owner, chat_ref, notify_chat=None):
    """گروه/کانال رو بررسی می‌کنه و اگه همه‌چیز اوکی بود تنظیم زمان رو توی پیوی صاحبش شروع می‌کنه."""
    info = api("getChat", chat_id=chat_ref)
    if not info.get("ok"):
        send_text(owner, "❌ این گروه/کانال رو پیدا نکردم. مطمئن شو ربات داخلش اضافه شده.")
        return "error"
    chat = info["result"]
    cid, ctype = chat["id"], chat["type"]
    if ctype == "private":
        return "error"
    kind = "channel" if ctype == "channel" else "group"
    title = chat.get("title") or str(cid)

    adm = api("getChatMember", chat_id=cid, user_id=owner).get("result", {}).get("status")
    if adm not in ("creator", "administrator"):
        send_text(owner, f"⛔️ فقط ادمین «{title}» می‌تونه ربات رو تنظیم کنه.")
        return "denied"

    ok, why = check_post_rights(cid, kind)
    if not ok:
        r = send_text(owner,
                      f"⚠️ دسترسی پیام دادن ربات در «{title}» بسته است.\n\n{why}\n\n"
                      "بعد از فعال کردنش دکمه‌ی زیر رو بزن:",
                      {"inline_keyboard": [[btn("🔄 بررسی مجدد", f"recheck:{cid}")]]})
        if not r.get("ok") and notify_chat:
            send_text(notify_chat, f"⚠️ {why}\n\nو بعدش وارد پیوی ربات شو: https://t.me/{BOT_NAME}")
        return "no_rights"

    ensure_target(cid, owner, title, kind)
    FLOW[owner] = {"chat_id": cid}
    WAIT.pop(owner, None)
    r = step_start(owner, cid)
    if not r.get("ok"):
        if notify_chat:
            send_text(notify_chat,
                      "❗️ اول وارد پیوی ربات شو و Start بزن، بعد دوباره اینجا /start بفرست:\n"
                      f"https://t.me/{BOT_NAME}")
        return "dm_failed"
    return "ok"


# ---------------------------------------------------------------- delivery
def deliver(t, price, closed=False):
    res = send_sticker(t["chat_id"], price, t.get("last_price"), closed)
    if res.get("ok"):
        t["last_price"] = price
        t["last_sent"] = time.time()
        t["last_slot"] = slot_key(t["interval"])
        t["retry_at"] = 0
        t["warned"] = False
        save()
        return True

    desc = (res.get("description") or "")
    low = desc.lower()
    print("❌ ارسال ناموفق:", t["title"], desc)
    gone = any(x in low for x in ("kicked", "blocked", "chat not found", "deactivated", "not a member",
                                  "bot was blocked"))
    rights = any(x in low for x in ("not enough rights", "have no rights", "rights to send",
                                    "not allowed", "administrator rights"))
    owner = t.get("owner")
    if gone:
        S["targets"].pop(str(t["chat_id"]), None)
        save()
        if owner and owner != t["chat_id"]:
            send_text(owner, f"🚫 ربات از «{t['title']}» حذف شده یا بسته شده. این مقصد پاک شد.")
    elif (rights or res.get("error_code") == 403) and not t.get("warned"):
        t["warned"] = True
        t["last_sent"] = time.time()
        save()
        if owner:
            send_text(owner,
                      f"⚠️ دسترسی پیام دادن ربات در «{t['title']}» بسته است و نمی‌تونم قیمت بفرستم.\n\n"
                      "لطفاً دسترسی ارسال پیام/استیکر رو برای ربات فعال کن و بعد دکمه‌ی زیر رو بزن:",
                      {"inline_keyboard": [[btn("🔄 بررسی مجدد", f"recheck:{t['chat_id']}")]]})
    elif res.get("error_code") == 429:
        time.sleep(res.get("parameters", {}).get("retry_after", 3))
    t["retry_at"] = time.time() + 60      # تلاش مجدد بعد از یک دقیقه ، نه هر چند ثانیه
    return False


def slot_key(interval):
    """شناسه‌ی بازه‌ی زمانی فعلی (مثلا برای ۱۵ دقیقه: هر ربع ساعت یک اسلات)"""
    n = tehran_now()
    return "%s-%d" % (n.strftime("%Y%m%d"), (n.hour * 60 + n.minute) // max(1, int(interval)))


def run_schedule():
    now = time.time()
    due = []
    for t in list(S["targets"].values()):
        if not t.get("ready") or not window_ok(t):
            continue
        if t.get("retry_at", 0) > now:
            continue
        iv = int(t["interval"])
        if iv in (15, 30, 60):
            # دقیقا سر ربع/نیم/ساعت (طبق ساعت تهران) ارسال میشه
            if t.get("last_slot") == slot_key(iv):
                continue
        elif now - t.get("last_sent", 0) < iv * 60 - 30:
            continue
        if t.get("warned") and now - t.get("last_sent", 0) < 3600:
            continue  # مشکل دسترسی داره؛ ساعتی یک‌بار دوباره امتحان می‌کنیم
        due.append(t)
    if not due:
        return
    try:
        price, closed = cached_price()
    except Exception as e:
        print("price error:", e)
        for t in due:
            t["retry_at"] = now + 30
        return
    for t in due:
        deliver(t, price, closed)


# ---------------------------------------------------------------- handlers
def handle_callback(cq):
    uid = cq["from"]["id"]
    data = cq.get("data", "")
    msg = cq.get("message") or {}
    mid = msg.get("message_id")
    api("answerCallbackQuery", callback_query_id=cq["id"])

    if data == "home":
        show_menu(uid, mid)
    elif data == "admin" or data == "admin:status":
        if uid != ADMIN_ID:
            return
        show_admin(uid, mid)
    elif data == "admin:api":
        if uid != ADMIN_ID:
            return
        WAIT[uid] = "api_url"
        show(uid, mid,
             "🔑 آدرس API را کامل بفرست.\n\nمثال:\nhttps://api.alanchand.com/?type=currencies&token=TOKEN\n\nفقط همین URL ذخیره می‌شود و قیمت دلار از بخش usd → sell خوانده می‌شود.",
             {"inline_keyboard": [[btn("🔙 انصراف", "admin")]]})
    elif data == "admin:clear":
        if uid != ADMIN_ID:
            return
        S["fake_price"] = None
        S["fake_last"] = None
        save()
        try:
            _PC["price"] = None
        except Exception:
            pass
        show_admin(uid, mid)
    elif data == "admin:set":
        if uid != ADMIN_ID:
            return
        WAIT[uid] = "fake_price"
        show(uid, mid, "✏️ قیمت دستی را به تومان بفرست (مثلاً 267304):",
             {"inline_keyboard": [[btn("🔙 انصراف", "admin")]]})
    elif data.startswith("admin:+") or data.startswith("admin:-"):
        if uid != ADMIN_ID:
            return
        try:
            delta = int(data.split(":")[1])
        except Exception:
            return
        cur = S.get("fake_price")
        if cur is None:
            try:
                cur, _ = get_price()
            except Exception:
                cur = 267000
        S["fake_last"] = cur
        S["fake_price"] = int(cur) + delta
        save()
        show_admin(uid, mid)
    elif data == "admin:test":
        if uid != ADMIN_ID:
            return
        try:
            price, closed = cached_price()
            last = S.get("fake_last")
            if last is None:
                last = price
            res = send_sticker(uid, price, last, closed)
            if res.get("ok"):
                S["fake_last"] = price
                save()
                api("answerCallbackQuery", callback_query_id=cq["id"], text="✅ استیکر ارسال شد")
            else:
                api("answerCallbackQuery", callback_query_id=cq["id"],
                    text="❌ " + (res.get("description") or "خطا")[:100], show_alert=True)
        except Exception as e:
            api("answerCallbackQuery", callback_query_id=cq["id"], text=f"❌ {e}", show_alert=True)
        return
    elif data == "list":
        show_list(uid, mid)
    elif data == "dest:me":
        ensure_target(uid, uid, "پیوی خودم", "user")
        FLOW[uid] = {"chat_id": uid}
        step_start(uid, uid, mid)
    elif data in ("dest:group", "dest:channel"):
        is_ch = data.endswith("channel")
        WAIT[uid] = "channel" if is_ch else "group"
        if is_ch:
            text = ("📢 برای کانال:\n\n"
                    "۱) ربات رو به کانال اضافه کن و «ادمین» کن (با دسترسی ارسال پیام)\n"
                    "۲) داخل کانال یک پیام /start بفرست\n\n"
                    "بعدش تنظیم زمان رو همین‌جا ازت می‌پرسم.\n"
                    "اگه /start کار نکرد، یه پیام از کانال همین‌جا فوروارد کن یا یوزرنیمش رو (مثل @mychannel) بفرست.")
            url = f"https://t.me/{BOT_NAME}?startchannel=true&admin=post_messages"
            label = "➕ افزودن ربات به کانال"
        else:
            text = ("👥 برای گروه:\n\n"
                    "۱) ربات رو به گروه اضافه کن و «ادمین» کن\n"
                    "۲) داخل گروه /start بفرست\n\n"
                    "بعدش تنظیم زمان رو همین‌جا ازت می‌پرسم.\n"
                    "اگه /start کار نکرد، یوزرنیم گروه رو (مثل @mygroup) همین‌جا بفرست.")
            url = f"https://t.me/{BOT_NAME}?startgroup=true"
            label = "➕ افزودن ربات به گروه"
        show(uid, mid, text, {"inline_keyboard": [[btn(label, url=url)], [btn("🏠 منو", "home")]]})
    elif data == "all24":
        f = FLOW.get(uid)
        if not f:
            show(uid, mid, "جلسه تموم شده. دوباره /start بزن.")
            return
        f["all24"] = True
        step_interval(uid, mid)
    elif data.startswith("sh:"):
        f = FLOW.get(uid)
        if not f:
            show(uid, mid, "جلسه تموم شده. دوباره /start بزن.")
            return
        f["start"] = int(data[3:])
        step_end(uid, mid, f["start"])
    elif data.startswith("eh:"):
        f = FLOW.get(uid)
        if not f:
            show(uid, mid, "جلسه تموم شده. دوباره /start بزن.")
            return
        f["end"] = int(data[3:])
        f["all24"] = False
        step_interval(uid, mid)
    elif data.startswith("iv:"):
        finish(uid, mid, int(data[3:]))
    elif data.startswith("recheck:"):
        cid = int(data[8:])
        t = S["targets"].get(str(cid))
        if t and t.get("ready"):
            ok, why = check_post_rights(cid, t["kind"] if t["kind"] != "user" else "group")
            if t["kind"] == "user" or ok:
                t["warned"] = False
                t["last_sent"] = 0
                save()
                show(uid, mid, f"✅ دسترسی فعاله. ارسال برای «{t['title']}» ادامه پیدا می‌کنه.")
            else:
                show(uid, mid, f"⚠️ هنوز بسته است.\n\n{why}",
                     {"inline_keyboard": [[btn("🔄 بررسی مجدد", f"recheck:{cid}")]]})
        else:
            register_chat(uid, cid)
    elif data.startswith(("cfg:", "edit:", "del:")):
        action, cid = data.split(":", 1)
        t = S["targets"].get(cid)
        if not t or t["owner"] != uid:
            show(uid, mid, "این مقصد پیدا نشد.", kb_menu(uid))
            return
        if action == "cfg":
            show(uid, mid, summary_text(t).replace("✅ تنظیمات ذخیره شد", "⚙️ تنظیمات فعلی"), kb_detail(t))
        elif action == "edit":
            FLOW[uid] = {"chat_id": t["chat_id"]}
            step_start(uid, t["chat_id"], mid)
        else:
            S["targets"].pop(cid, None)
            save()
            show(uid, mid, f"🗑 «{t['title']}» حذف شد.", kb_menu(uid))


def parse_cmd(text):
    """('/start', None) یا ('/start', 'botname')"""
    if not text.startswith("/"):
        return "", None
    first = text.split()[0]
    name = None
    if "@" in first:
        first, name = first.split("@", 1)
    return first.lower(), name


def handle_message(msg):
    chat = msg["chat"]
    text = (msg.get("text") or "").strip()
    frm = msg.get("from") or {}
    uid = frm.get("id")
    cmd, target_bot = parse_cmd(text)

    if chat["type"] == "private":
        print("📩 پیام رسید:", text[:40], "از", uid)
        if cmd in ("/start", "/settings", "/menu"):
            show_menu(uid)
            return
        if cmd == "/admin" and uid == ADMIN_ID:
            show_admin(uid)
            return
        if cmd == "/price" and uid == ADMIN_ID:
            send_text(uid, "⏳ در حال دریافت قیمت از API ...")
            try:
                send_text(uid, format_report(price_report()))
            except Exception as e:
                send_text(uid, "❌ خطا: %s" % e)
            return
        if cmd == "/stop":
            show_list(uid)
            return
        # دریافت URL API از ادمین
        if WAIT.get(uid) == "api_url" and uid == ADMIN_ID:
            WAIT.pop(uid, None)
            url = text.strip()
            if not re.match(r"^https?://", url, re.I):
                send_text(uid, "❌ آدرس API معتبر نیست. باید با http:// یا https:// شروع شود.",
                          {"inline_keyboard": [[btn("🔙 پنل", "admin")]]})
                return
            S["api_url"] = url
            save()
            _API_CACHE.update(ts=0, price=None, sell=None, buy=None, updated_at=None)
            _PC["price"] = None
            show_admin(uid)
            return

        # دریافت قیمت فیک از ادمین
        if WAIT.get(uid) == "fake_price" and uid == ADMIN_ID:
            WAIT.pop(uid, None)
            raw = text.replace(",", "").replace("،", "").replace(" ", "")
            try:
                val = int(float(raw))
                if val < 1000 or val > 10_000_000:
                    raise ValueError("range")
                S["fake_last"] = S.get("fake_price")
                S["fake_price"] = val
                save()
                show_admin(uid)
            except Exception:
                send_text(uid, "❌ عدد معتبر بفرست (مثلاً 267304)",
                          {"inline_keyboard": [[btn("🔙 پنل", "admin")]]})
            return
        # فوروارد از کانال/گروه
        fo = msg.get("forward_origin") or {}
        fchat = fo.get("chat") if fo.get("type") in ("channel", "chat") else msg.get("forward_from_chat")
        if fchat:
            register_chat(uid, fchat["id"])
            return
        if re.fullmatch(r"@[A-Za-z0-9_]{4,}|-100\d+", text):
            register_chat(uid, text)
            return
        send_text(uid, "برای شروع /start بزن 👇", kb_menu(uid))
        return

    # گروه / سوپرگروه
    if cmd == "/start" and (target_bot is None or target_bot.lower() == BOT_NAME.lower()):
        print("📩 /start توی گروه:", chat.get("title"), "از", uid)
        if uid:
            register_chat(uid, chat["id"], notify_chat=chat["id"])


def handle_channel_post(post):
    cmd, target_bot = parse_cmd((post.get("text") or "").strip())
    if cmd != "/start" or (target_bot and target_bot.lower() != BOT_NAME.lower()):
        return
    cid = post["chat"]["id"]
    print("📩 /start توی کانال:", post["chat"].get("title"))
    owner = owner_for(cid)
    api("deleteMessage", chat_id=cid, message_id=post["message_id"])  # اگه دسترسی حذف داشت
    if not owner:
        return
    res = register_chat(owner, cid)
    if res == "dm_failed":
        send_text(cid, "❗️ ادمین کانال باید اول وارد پیوی ربات بشه و Start بزنه:\n"
                       f"https://t.me/{BOT_NAME}")


def handle_my_chat_member(m):
    chat = m["chat"]
    if chat["type"] == "private":
        return
    new = m["new_chat_member"]["status"]
    frm = m["from"]["id"]
    cid = str(chat["id"])
    if new in ("administrator", "member"):
        S["pending"][cid] = frm
        save()
        kind = "کانال" if chat["type"] == "channel" else "گروه"
        send_text(frm, f"✅ ربات به «{chat.get('title')}» اضافه شد.\n"
                       f"حالا داخل همون {kind} یک پیام /start بفرست تا تنظیم زمان رو شروع کنم.")
    elif new in ("left", "kicked"):
        if S["targets"].pop(cid, None):
            save()


def handle_update(u):
    if "callback_query" in u:
        handle_callback(u["callback_query"])
    elif "message" in u:
        handle_message(u["message"])
    elif "channel_post" in u:
        handle_channel_post(u["channel_post"])
    elif "my_chat_member" in u:
        handle_my_chat_member(u["my_chat_member"])


# ---------------------------------------------------------------- main
def self_test():
    global BOT_ID, BOT_NAME
    print("۱) چک قیمت دلار ...")
    try:
        p, c = get_price()
        print("   ✅ قیمت دریافت شد:", fmt_price(p), "تومان", "(بر پایه تتر - بازار بسته)" if c else "(دلار آزاد)")
    except Exception as e:
        print("   ❌ قیمت از API دریافت نشد.", "\n   جزئیات:", e)

    print("۲) چک اتصال به تلگرام ...")
    while True:
        r = api("getMe", _timeout=15)
        if r.get("ok"):
            BOT_ID = r["result"]["id"]
            BOT_NAME = r["result"]["username"]
            print(f"   ✅ وصل شد. ربات: @{BOT_NAME}")
            return
        if r.get("error_code") in (401, 404):
            print("   ❌ توکن اشتباهه یا باطل شده. از BotFather توکن جدید بگیر و بالای فایل بذار.")
            raise SystemExit
        print("   ❌ به تلگرام وصل نمیشم. VPN رو روشن کن (باید کل گوشی رو بگیره). ۱۰ ثانیه دیگه دوباره تلاش میکنم ...")
        time.sleep(10)


def main():
    self_test()
    api("deleteWebhook", _timeout=15)
    load_state()
    print(f"Bot started. مقصدهای ذخیره‌شده: {len(S['targets'])}")
    offset = None
    last_sched = 0
    while True:
        params = {"timeout": 8,
                  "allowed_updates": ["message", "callback_query", "channel_post", "my_chat_member"]}
        if offset:
            params["offset"] = offset
        ups = api("getUpdates", _timeout=35, **params)
        if not ups.get("ok"):
            print("❌ تلگرام خطا داد:", ups.get("description"))
            if ups.get("error_code") == 409:
                print("   یعنی یه نسخه‌ی دیگه از همین ربات هم اجراست (مثلا پایروید یا یه دیپلوی قدیمی). بقیه رو ببند.")
            time.sleep(10)
        else:
            for u in ups.get("result", []):
                offset = u["update_id"] + 1
                try:
                    handle_update(u)
                except Exception:
                    traceback.print_exc()
        if time.time() - last_sched >= 5:
            last_sched = time.time()
            try:
                run_schedule()
            except Exception:
                traceback.print_exc()


if __name__ == "__main__":
    main()
